// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMfpCB3BnAWK4HoGvI0STd4S6wjjmWwLg',
    appId: '1:968667676404:android:70aa8c2c0fb68b3c65a8a1',
    messagingSenderId: '968667676404',
    projectId: 'nursing-4accd',
    storageBucket: 'nursing-4accd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt-d8gXxIyoxigykiggsfFyvaXjSx4Rvo',
    appId: '1:968667676404:ios:d8c57d59e3438c2d65a8a1',
    messagingSenderId: '968667676404',
    projectId: 'nursing-4accd',
    storageBucket: 'nursing-4accd.firebasestorage.app',
    iosBundleId: 'codience.travel.agencies.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBASQdd6Ratgtc-ijbsuYQAySJKltbpvDQ',
    appId: '1:968667676404:web:20c14dedc7352ca865a8a1',
    messagingSenderId: '968667676404',
    projectId: 'nursing-4accd',
    authDomain: 'nursing-4accd.firebaseapp.com',
    storageBucket: 'nursing-4accd.firebasestorage.app',
    measurementId: 'G-NBXBGT30GB',
  );
}
