// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

// ignore_for_file: prefer_single_quotes, avoid_renaming_method_parameters, constant_identifier_names

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

class CodegenLoader extends AssetLoader{
  const CodegenLoader();

  @override
  Future<Map<String, dynamic>?> load(String path, Locale locale) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static const Map<String,dynamic> _zh = {
  "hello": "你好",
  "choose_image": "选择图片",
  "take_photo": "拍照",
  "choose_from_gallery": "从相册选择",
  "back_to_role_selection": "返回角色选择",
  "login_as_customer": "作为顾客登录",
  "enter_credentials_to_continue": "输入凭证以继续",
  "continue_with_google": "通过Google继续",
  "continue_with_apple": "通过Apple继续",
  "or_continue_with_email": "或通过电子邮件继续",
  "email_address": "电子邮件地址",
  "email_placeholder": "you@example.com",
  "email_required": "必须要有电子邮件",
  "email_invalid": "无效的电子邮件地址",
  "phone_number_required": "必须要有电话号码",
  "phone_number_invalid": "无效的电话号码",
  "search_country": "搜索国家",
  "otp_title": "验证码",
  "otp_subtitle": "我们已向您的手机号码发送了验证码",
  "verify": "验证",
  "resend_code": "重新发送验证码",
  "didnt_receive_code": "没有收到验证码？",
  "otp_invalid": "验证码无效",
  "password": "密码",
  "password_placeholder": "••••••••",
  "password_required": "必须要有密码",
  "password_length_error": "密码必须至少为6个字符",
  "remember_me": "记住我",
  "forgot_password": "忘记密码？",
  "login": "登录",
  "dont_have_account": "还没有账号？",
  "register_now": "立即注册",
  "language_english": "English",
  "language_arabic": "العربية",
  "language_german": "Deutsch",
  "language_spanish": "Español",
  "language_french": "Français",
  "language_italian": "Italiano",
  "language_russian": "Русский",
  "register_as_customer": "作为顾客注册",
  "create_account_to_get_started": "创建账号以开始",
  "or_register_with_email": "或通过电子邮件注册",
  "full_name": "全名",
  "full_name_placeholder": "张三",
  "phone_number": "电话号码",
  "phone_placeholder": "+86 138 0013 8000",
  "confirm_password": "确认密码",
  "confirm_password_placeholder": "••••••••",
  "i_agree_to_the": "我同意",
  "terms_of_service": "服务条款",
  "and": "和",
  "privacy_policy": "隐私政策",
  "create_account": "创建账号",
  "already_have_account": "已经有账号？",
  "login_here": "在此登录",
  "discover_egypt": "探索埃及",
  "book_amazing_activities": "预订精彩活动和体验",
  "scan_qr_code": "扫描二维码",
  "search_activities": "搜索活动...",
  "popular_activities": "热门活动",
  "special_events": "特别活动",
  "additional_services": "附加服务",
  "luxor_temple_tour": "卢克索神庙之旅",
  "hours": "小时",
  "per_person": "/人",
  "book": "预订",
  "book_now": "立即预订",
  "healthcare": "医疗保健",
  "medical_support": "24/7 医疗支持",
  "spa_massage": "水疗与按摩",
  "relaxation_services": "放松服务",
  "request_service": "请求服务",
  "christmas_beach_party": "圣诞海滩派对",
  "new_year_gala_dinner": "新年晚宴",
  "special_event": "特别活动",
  "december": "十二月",
  "cultural": "文化",
  "home": "主页",
  "excursions": "短途旅行",
  "events": "活动",
  "services": "服务",
  "favorites": "收藏",
  "search_placeholder": "搜索短途旅行，活动...",
  "all": "全部",
  "snorkeling": "浮潜",
  "diving": "潜水",
  "safari": "通过",
  "adventure": "冒险",
  "view_all": "查看全部",
  "trending_excursions": "热门短途旅行",
  "upcoming_events": "即将到来的活动",
  "quick_services": "快速服务",
  "connect": "连接",
  "available": "可用",
  "explore_excursions": "探索短途旅行",
  "my_favorites": "我的收藏",
  "no_favorites_yet": "暂无收藏",
  "start_adding_favorites": "开始添加收藏！",
  "favorite_excursions": "收藏的短途旅行",
  "favorite_events": "收藏的活动",
  "connect_with_representative": "联系代表",
  "scan_qr_description": "扫描代表的二维码以开始",
  "close": "关闭",
  "select_date": "选择日期",
  "preferred_time": "首选时间",
  "number_of_people": "人数",
  "additional_notes": "附加说明",
  "additional_notes_placeholder": "任何特殊要求或需求...",
  "price_summary": "价格汇总",
  "service_fee": "服务费",
  "total": "总计",
  "cancel": "取消",
  "confirm_booking": "确认预订",
  "people": "人",
  "person": "人",
  "preferred_date": "首选日期",
  "urgency_level": "紧急程度",
  "normal": "正常",
  "urgent": "紧急",
  "emergency": "急诊",
  "additional_details": "附加详情",
  "additional_details_placeholder": "请描述您的需求或任何具体要求...",
  "service_request_info": "我们的团队将在30分钟内联系您确认服务请求",
  "submit_request": "提交请求",
  "booking_confirmed": "预订已确认！",
  "service_requested": "服务请求已提交！",
  "night_life": "夜生活",
  "christmas": "圣诞节",
  "new_year": "新年",
  "select_time": "选择时间",
  "excursion_red_sea_name": "红海浮潜探险",
  "excursion_red_sea_desc": "探索美丽的珊瑚礁和多彩的海洋生物",
  "excursion_safari_name": "沙漠野生动物园体验",
  "excursion_safari_desc": "惊险刺激的沙漠探险，骑四轮摩托和骆驼",
  "excursion_scuba_name": "专业潜水",
  "excursion_scuba_desc": "由认证教练带领的深海潜水体验",
  "excursion_luxor_name": "卢克索神庙之旅",
  "excursion_luxor_desc": "参观古埃及神庙和纪念碑",
  "excursion_bedouin_name": "贝都因夜间野生动物园",
  "excursion_bedouin_desc": "体验贝都因文化，享受晚餐和观星",
  "excursion_parasailing_name": "滑翔伞探险",
  "excursion_parasailing_desc": "飞越红海，欣赏壮丽景色",
  "event_christmas_party_name": "圣诞海滩派对",
  "event_christmas_party_desc": "在海滩上伴随音乐和美食庆祝圣诞",
  "event_new_year_gala_name": "新年庆典之夜",
  "event_new_year_gala_desc": "以盛大的庆典迎接新年",
  "event_night_club_name": "夜总会体验",
  "event_night_club_desc": "拥有国际DJ的高级夜总会体验",
  "event_cultural_night_name": "埃及文化之夜",
  "event_cultural_night_desc": "传统的埃及音乐，舞蹈和美食",
  "service_healthcare_name": "医疗保健",
  "service_healthcare_desc": "24/7 医疗支持",
  "service_spa_name": "水疗与按摩",
  "service_spa_desc": "放松服务",
  "service_doctor_name": "医生咨询",
  "service_doctor_desc": "在线和面对面",
  "service_transfer_name": "机场接送",
  "service_transfer_desc": "私人交通",
  "service_trainer_name": "私人教练",
  "service_trainer_desc": "健身与健康",
  "service_guide_name": "导游",
  "service_guide_desc": "私人旅游",
  "upcoming_bookings": "即将到来的预订",
  "my_bookings": "我的预订",
  "days_until": "天直到",
  "today": "今天",
  "tomorrow": "明天",
  "cancel_booking": "取消",
  "no_upcoming_bookings": "没有即将到来的预订",
  "booking_cancelled": "预订已成功取消",
  "confirm": "确认",
  "offers": "优惠",
  "real_estate": "房地产",
  "shaleeh": "小木屋",
  "studio": "单间公寓",
  "department": "公寓",
  "villa": "别墅",
  "select_city": "选择城市",
  "onboarding_title_1": "探索世界",
  "onboarding_subtitle_1": "发现为您量身定制的隐藏瑰宝和令人惊叹的目的地。",
  "onboarding_title_2": "奢华住宿",
  "onboarding_subtitle_2": "在精心挑选的酒店和独特的住宿中体验世界级的款待。",
  "onboarding_title_3": "轻松旅程",
  "onboarding_subtitle_3": "轻松规划和预订您的整个行程，从航班到当地旅游。",
  "get_started": "开始吧",
  "skip": "跳过"
};
static const Map<String,dynamic> _ja = {
  "hello": "こんにちは",
  "choose_image": "画像を選択",
  "take_photo": "写真を撮る",
  "choose_from_gallery": "ギャラリーから選択",
  "back_to_role_selection": "役割選択に戻る",
  "login_as_customer": "顧客としてログイン",
  "enter_credentials_to_continue": "続行するには資格情報を入力してください",
  "continue_with_google": "Googleで続行",
  "continue_with_apple": "Appleで続行",
  "or_continue_with_email": "またはメールで続行",
  "email_address": "メールアドレス",
  "email_placeholder": "you@example.com",
  "email_required": "メールアドレスが必要です",
  "email_invalid": "無効なメールアドレス",
  "phone_number_required": "電話番号が必要です",
  "phone_number_invalid": "無効な電話番号",
  "search_country": "国を検索",
  "otp_title": "認証コード",
  "otp_subtitle": "認証コードを電話番号に送信しました",
  "verify": "確認",
  "resend_code": "コードを再送信",
  "didnt_receive_code": "コードが届きませんか？",
  "otp_invalid": "無効な認証コードです",
  "password": "パスワード",
  "password_placeholder": "••••••••",
  "password_required": "パスワードが必要です",
  "password_length_error": "パスワードは6文字以上である必要があります",
  "remember_me": "ログイン状態を保持",
  "forgot_password": "パスワードをお忘れですか？",
  "login": "ログイン",
  "dont_have_account": "アカウントをお持ちでないですか？",
  "register_now": "今すぐ登録",
  "language_english": "English",
  "language_arabic": "العربية",
  "language_german": "Deutsch",
  "language_spanish": "Español",
  "language_french": "Français",
  "language_italian": "Italiano",
  "language_russian": "Русский",
  "register_as_customer": "顧客として登録",
  "create_account_to_get_started": "アカウントを作成して開始",
  "or_register_with_email": "またはメールで登録",
  "full_name": "氏名",
  "full_name_placeholder": "山田 太郎",
  "phone_number": "電話番号",
  "phone_placeholder": "+81 90 1234 5678",
  "confirm_password": "パスワード（確認）",
  "confirm_password_placeholder": "••••••••",
  "i_agree_to_the": "私は同意します",
  "terms_of_service": "利用規約",
  "and": "および",
  "privacy_policy": "プライバシーポリシー",
  "create_account": "アカウント作成",
  "already_have_account": "すでにアカウントをお持ちですか？",
  "login_here": "こちらからログイン",
  "discover_egypt": "エジプトを発見",
  "book_amazing_activities": "素晴らしいアクティビティや体験を予約",
  "scan_qr_code": "QRコードをスキャン",
  "search_activities": "アクティビティを検索...",
  "popular_activities": "人気のアクティビティ",
  "special_events": "特別イベント",
  "additional_services": "追加サービス",
  "luxor_temple_tour": "ルクソール神殿ツアー",
  "hours": "時間",
  "per_person": "/人",
  "book": "予約",
  "book_now": "今すぐ予約",
  "healthcare": "ヘルスケア",
  "medical_support": "24時間年中無休の医療サポート",
  "spa_massage": "スパ＆マッサージ",
  "relaxation_services": "リラクゼーションサービス",
  "request_service": "サービスをリクエスト",
  "christmas_beach_party": "クリスマスビーチパーティー",
  "new_year_gala_dinner": "ニューイヤーガラディナー",
  "special_event": "特別イベント",
  "december": "12月",
  "cultural": "文化",
  "home": "ホーム",
  "excursions": "小旅行",
  "events": "イベント",
  "services": "サービス",
  "favorites": "お気に入り",
  "search_placeholder": "小旅行やイベントを検索...",
  "all": "すべて",
  "snorkeling": "シュノーケリング",
  "diving": "ダイビング",
  "safari": "サファリ",
  "adventure": "冒険",
  "view_all": "すべて表示",
  "trending_excursions": "トレンドの小旅行",
  "upcoming_events": "今後のイベント",
  "quick_services": "クイックサービス",
  "connect": "接続",
  "available": "利用可能",
  "explore_excursions": "小旅行を探索",
  "my_favorites": "私のお気に入り",
  "no_favorites_yet": "お気に入りはまだありません",
  "start_adding_favorites": "お気に入りの追加を始めましょう！",
  "favorite_excursions": "お気に入りの小旅行",
  "favorite_events": "お気に入りのイベント",
  "connect_with_representative": "担当者と連絡を取る",
  "scan_qr_description": "担当者のQRコードをスキャンして開始",
  "close": "閉じる",
  "select_date": "日付を選択",
  "preferred_time": "希望時間",
  "number_of_people": "人数",
  "additional_notes": "追加の注意点",
  "additional_notes_placeholder": "特別なリクエストや要件...",
  "price_summary": "価格概要",
  "service_fee": "サービス料",
  "total": "合計",
  "cancel": "キャンセル",
  "confirm_booking": "予約を確定",
  "people": "人",
  "person": "人",
  "preferred_date": "希望日",
  "urgency_level": "緊急度",
  "normal": "通常",
  "urgent": "緊急",
  "emergency": "非常事態",
  "additional_details": "追加詳細",
  "additional_details_placeholder": "ニーズや具体的な要件をご記入ください...",
  "service_request_info": "30分以内にチームから確認のご連絡をいたします",
  "submit_request": "リクエストを送信",
  "booking_confirmed": "予約確定！",
  "service_requested": "サービスリクエスト送信完了！",
  "night_life": "ナイトライフ",
  "christmas": "クリスマス",
  "new_year": "新年",
  "select_time": "時間を選択",
  "excursion_red_sea_name": "紅海シュノーケリングアドベンチャー",
  "excursion_red_sea_desc": "美しいサンゴ礁と色鮮やかな海洋生物を探索",
  "excursion_safari_name": "砂漠サファリ体験",
  "excursion_safari_desc": "四輪バギーやラクダ乗りを楽しむスリリングな砂漠の冒険",
  "excursion_scuba_name": "プロフェッショナルスキューバダイビング",
  "excursion_scuba_desc": "認定インストラクターによる深海ダイビング体験",
  "excursion_luxor_name": "ルクソール神殿ツアー",
  "excursion_luxor_desc": "古代エジプトの神殿や記念碑を訪問",
  "excursion_bedouin_name": "ベドウィンナイトサファリ",
  "excursion_bedouin_desc": "夕食と星空観察でベドウィン文化を体験",
  "excursion_parasailing_name": "パラセーリングアドベンチャー",
  "excursion_parasailing_desc": "息を呑むような景色とともに紅海の上空を飛ぶ",
  "event_christmas_party_name": "クリスマスビーチパーティー",
  "event_christmas_party_desc": "音楽と食事でビーチでのクリスマスをお祝い",
  "event_new_year_gala_name": "ニューイヤーガラナイト",
  "event_new_year_gala_desc": "壮大な祝賀会で新年を迎える",
  "event_night_club_name": "ナイトクラブ体験",
  "event_night_club_desc": "国際的なDJによるプレミアムナイトクラブ体験",
  "event_cultural_night_name": "エジプト文化の夜",
  "event_cultural_night_desc": "伝統的なエジプトの音楽、ダンス、料理",
  "service_healthcare_name": "ヘルスケア",
  "service_healthcare_desc": "24時間年中無休の医療サポート",
  "service_spa_name": "スパ＆マッサージ",
  "service_spa_desc": "リラクゼーションサービス",
  "service_doctor_name": "医師の診察",
  "service_doctor_desc": "オンラインおよび対面",
  "service_transfer_name": "空港送迎",
  "service_transfer_desc": "プライベート輸送",
  "service_trainer_name": "パーソナルトレーナー",
  "service_trainer_desc": "フィットネス＆ウェルネス",
  "service_guide_name": "ツアーガイド",
  "service_guide_desc": "プライベートツアー",
  "offers": "オファー",
  "real_estate": "不動産",
  "shaleeh": "シャレー",
  "studio": "スタジオ",
  "department": "マンション",
  "villa": "ヴィラ",
  "select_city": "都市を選択",
  "onboarding_title_1": "世界を探索する",
  "onboarding_subtitle_1": "あなたにぴったりの隠れた名所や息を呑むような目的地を発見してください。",
  "onboarding_title_2": "ラグジュアリーな滞在",
  "onboarding_subtitle_2": "厳選されたホテルやユニークな滞在先で、ワールドクラスのおもてなしを体験してください。",
  "onboarding_title_3": "楽な旅",
  "onboarding_subtitle_3": "フライトからローカルツアーまで、旅行全体を簡単に計画・予約できます。",
  "get_started": "始める",
  "skip": "スキップ"
};
static const Map<String,dynamic> _de = {
  "hello": "Hallo",
  "choose_image": "Bild auswählen",
  "take_photo": "Foto aufnehmen",
  "choose_from_gallery": "Aus der Galerie wählen",
  "back_to_role_selection": "Zurück zur Rollenauswahl",
  "login_as_customer": "Als Kunde anmelden",
  "enter_credentials_to_continue": "Geben Sie Ihre Anmeldedaten ein, um fortzufahren",
  "continue_with_google": "Mit Google fortfahren",
  "continue_with_apple": "Mit Apple fortfahren",
  "or_continue_with_email": "Oder mit E-Mail fortfahren",
  "email_address": "E-Mail-Adresse",
  "email_placeholder": "you@example.com",
  "email_required": "E-Mail ist erforderlich",
  "email_invalid": "Ungültige E-Mail-Adresse",
  "phone_number_required": "Telefonnummer ist erforderlich",
  "phone_number_invalid": "Ungültige Telefonnummer",
  "search_country": "Land suchen",
  "otp_title": "Bestätigungscode",
  "otp_subtitle": "Wir haben einen Bestätigungscode an Ihre Telefonnummer gesendet",
  "verify": "Bestätigen",
  "resend_code": "Code erneut senden",
  "didnt_receive_code": "Keinen Code erhalten?",
  "otp_invalid": "Ungültiger Bestätigungscode",
  "password": "Passwort",
  "password_placeholder": "••••••••",
  "password_required": "Passwort ist erforderlich",
  "password_length_error": "Passwort muss mindestens 6 Zeichen lang sein",
  "remember_me": "Angemeldet bleiben",
  "forgot_password": "Passwort vergessen?",
  "login": "Anmelden",
  "dont_have_account": "Haben Sie noch kein Konto?",
  "register_now": "Jetzt registrieren",
  "register_as_customer": "Als Kunde registrieren",
  "create_account_to_get_started": "Erstellen Sie Ihr Konto, um zu beginnen",
  "or_register_with_email": "Oder mit E-Mail registrieren",
  "full_name": "Vollständiger Name",
  "full_name_placeholder": "Max Mustermann",
  "phone_number": "Telefonnummer",
  "phone_placeholder": "+49 123 456 7890",
  "confirm_password": "Passwort bestätigen",
  "confirm_password_placeholder": "••••••••",
  "i_agree_to_the": "Ich stimme den",
  "terms_of_service": "Nutzungsbedingungen",
  "and": "und",
  "privacy_policy": "Datenschutzrichtlinie",
  "create_account": "Konto erstellen",
  "already_have_account": "Haben Sie bereits ein Konto?",
  "login_here": "Hier anmelden",
  "discover_egypt": "Ägypten entdecken",
  "book_amazing_activities": "Buchen Sie erstaunliche Aktivitäten und Erlebnisse",
  "scan_qr_code": "QR-Code scannen",
  "search_activities": "Aktivitäten suchen...",
  "popular_activities": "Beliebte Aktivitäten",
  "special_events": "Besondere Veranstaltungen",
  "additional_services": "Zusätzliche Dienstleistungen",
  "luxor_temple_tour": "Luxor Tempel Tour",
  "hours": "Stunden",
  "per_person": "/Person",
  "book": "Buchen",
  "book_now": "Jetzt buchen",
  "healthcare": "Gesundheitswesen",
  "medical_support": "24/7 Medizinische Unterstützung",
  "spa_massage": "Spa & Massage",
  "relaxation_services": "Entspannungsdienstleistungen",
  "request_service": "Service anfordern",
  "christmas_beach_party": "Weihnachts-Strandparty",
  "new_year_gala_dinner": "Neujahrs-Gala-Dinner",
  "special_event": "Besonderes Ereignis",
  "december": "Dezember",
  "cultural": "Kulturell",
  "language_english": "English",
  "language_arabic": "العربية",
  "language_german": "Deutsch",
  "language_spanish": "Español",
  "language_french": "Français",
  "language_italian": "Italiano",
  "language_russian": "Русский",
  "home": "Start",
  "excursions": "Ausflüge",
  "events": "Events",
  "services": "Dienste",
  "favorites": "Favoriten",
  "search_placeholder": "Ausflüge, Events suchen...",
  "all": "Alle",
  "snorkeling": "Schnorcheln",
  "diving": "Tauchen",
  "safari": "Safari",
  "adventure": "Abenteuer",
  "view_all": "Alle anzeigen",
  "trending_excursions": "Beliebte Ausflüge",
  "upcoming_events": "Kommende Events",
  "quick_services": "Schnelldienste",
  "connect": "Kontakt",
  "available": "Verfügbar",
  "explore_excursions": "Ausflüge entdecken",
  "my_favorites": "Meine Favoriten",
  "no_favorites_yet": "Noch keine Favoriten",
  "start_adding_favorites": "Fügen Sie Favoriten hinzu!",
  "favorite_excursions": "Lieblingsausflüge",
  "favorite_events": "Lieblingsevents",
  "connect_with_representative": "Vertreter kontaktieren",
  "scan_qr_description": "QR-Code scannen zum Starten",
  "close": "Schließen",
  "select_date": "Datum",
  "preferred_time": "Zeit",
  "number_of_people": "Personen",
  "additional_notes": "Notizen",
  "additional_notes_placeholder": "Sonderwünsche...",
  "price_summary": "Preis",
  "service_fee": "Gebühr",
  "total": "Gesamt",
  "cancel": "Abbrechen",
  "confirm_booking": "Bestätigen",
  "people": "Personen",
  "person": "Person",
  "preferred_date": "Wunschdatum",
  "urgency_level": "Dringlichkeit",
  "normal": "Normal",
  "urgent": "Dringend",
  "emergency": "Notfall",
  "additional_details": "Details",
  "additional_details_placeholder": "Beschreiben Sie Ihre Bedürfnisse...",
  "service_request_info": "Wir melden uns in 30 Min.",
  "submit_request": "Senden",
  "booking_confirmed": "Bestätigt!",
  "service_requested": "Gesendet!",
  "night_life": "Nachtleben",
  "christmas": "Weihnachten",
  "new_year": "Neujahr",
  "select_time": "Zeit",
  "excursion_red_sea_name": "Rotes Meer Schnorchel-Abenteuer",
  "excursion_red_sea_desc": "Entdecken Sie die wunderschönen Korallenriffe und das bunte Meeresleben",
  "excursion_safari_name": "Wüsten-Safari Erlebnis",
  "excursion_safari_desc": "Aufregendes Wüstenabenteuer mit Quads und Kamelreiten",
  "excursion_scuba_name": "Professionelles Tauchen",
  "excursion_scuba_desc": "Tiefseetaucherlebnis mit zertifizierten Tauchlehrern",
  "excursion_luxor_name": "Luxor Tempel Tour",
  "excursion_luxor_desc": "Besuchen Sie alte ägyptische Tempel und Denkmäler",
  "excursion_bedouin_name": "Beduinen Nacht-Safari",
  "excursion_bedouin_desc": "Erleben Sie die Beduinenkultur mit Abendessen und Sternenbeobachtung",
  "excursion_parasailing_name": "Parasailing Abenteuer",
  "excursion_parasailing_desc": "Schweben Sie über dem Roten Meer mit atemberaubender Aussicht",
  "event_christmas_party_name": "Weihnachts-Strandparty",
  "event_christmas_party_desc": "Feiern Sie Weihnachten am Strand mit Musik und Essen",
  "event_new_year_gala_name": "Neujahrs-Gala-Nacht",
  "event_new_year_gala_desc": "Begrüßen Sie das neue Jahr mit einer spektakulären Feier",
  "event_night_club_name": "Nachtclub-Erlebnis",
  "event_night_club_desc": "Premium-Nachtclub-Erlebnis mit internationalen DJs",
  "event_cultural_night_name": "Ägyptische Kulturnacht",
  "event_cultural_night_desc": "Traditionelle ägyptische Musik, Tanz und Küche",
  "service_healthcare_name": "Gesundheitswesen",
  "service_healthcare_desc": "24/7 Medizinische Unterstützung",
  "service_spa_name": "Spa & Massage",
  "service_spa_desc": "Entspannungsdienste",
  "service_doctor_name": "Arztkonsultation",
  "service_doctor_desc": "Online & Persönlich",
  "service_transfer_name": "Flughafentransfer",
  "service_transfer_desc": "Privater Transport",
  "service_trainer_name": "Personal Trainer",
  "service_trainer_desc": "Fitness & Wellness",
  "service_guide_name": "Reiseleiter",
  "service_guide_desc": "Private Touren",
  "upcoming_bookings": "Bevorstehende Buchungen",
  "my_bookings": "Meine Buchungen",
  "days_until": "Tage bis",
  "today": "Heute",
  "tomorrow": "Morgen",
  "cancel_booking": "Stornieren",
  "no_upcoming_bookings": "Keine bevorstehenden Buchungen",
  "booking_cancelled": "Buchung erfolgreich storniert",
  "confirm": "Bestätigen",
  "offers": "Angebote",
  "real_estate": "Immobilien",
  "shaleeh": "Chalet",
  "studio": "Studio",
  "department": "Wohnung",
  "villa": "Villa",
  "select_city": "Stadt auswählen",
  "onboarding_title_1": "Entdecke die Welt",
  "onboarding_subtitle_1": "Entdecken Sie versteckte Schätze und atemberaubende Reiseziele, die genau auf Sie zugeschnitten sind.",
  "onboarding_title_2": "Luxusaufenthalte",
  "onboarding_subtitle_2": "Erleben Sie erstklassige Gastfreundschaft in handverlesenen Hotels und einzigartigen Unterkünften.",
  "onboarding_title_3": "Müheloses Reisen",
  "onboarding_subtitle_3": "Planen und buchen Sie Ihre gesamte Reise mit Leichtigkeit, von Flügen bis hin zu lokalen Touren.",
  "get_started": "Loslegen",
  "skip": "Überspringen"
};
static const Map<String,dynamic> _ru = {
  "hello": "Привет",
  "choose_image": "Выбрать изображение",
  "take_photo": "Сделать фото",
  "choose_from_gallery": "Выбрать из галереи",
  "back_to_role_selection": "Вернуться к выбору роли",
  "login_as_customer": "Войти как клиент",
  "enter_credentials_to_continue": "Введите свои данные для продолжения",
  "continue_with_google": "Продолжить с Google",
  "continue_with_apple": "Продолжить с Apple",
  "or_continue_with_email": "Или продолжить с электронной почтой",
  "email_address": "Адрес электронной почты",
  "email_placeholder": "you@example.com",
  "email_required": "Требуется электронная почта",
  "email_invalid": "Неверный адрес электронной почты",
  "phone_number_required": "Требуется номер телефона",
  "phone_number_invalid": "Неверный номер телефона",
  "search_country": "Поиск страны",
  "otp_title": "Код подтверждения",
  "otp_subtitle": "Мы отправили код подтверждения на ваш номер телефона",
  "verify": "Подтвердить",
  "resend_code": "Отправить код повторно",
  "didnt_receive_code": "Не получили код?",
  "otp_invalid": "Неверный код подтверждения",
  "password": "Пароль",
  "password_placeholder": "••••••••",
  "password_required": "Требуется пароль",
  "password_length_error": "Пароль должен содержать не менее 6 символов",
  "remember_me": "Запомнить меня",
  "forgot_password": "Забыли пароль?",
  "login": "Войти",
  "dont_have_account": "Нет аккаунта?",
  "register_now": "Зарегистрироваться сейчас",
  "register_as_customer": "Зарегистрироваться как клиент",
  "create_account_to_get_started": "Создайте свой аккаунт, чтобы начать",
  "or_register_with_email": "Или зарегистрироваться с электронной почтой",
  "full_name": "Полное имя",
  "full_name_placeholder": "Иван Иванов",
  "phone_number": "Номер телефона",
  "phone_placeholder": "+7 123 456 7890",
  "confirm_password": "Подтвердить пароль",
  "confirm_password_placeholder": "••••••••",
  "i_agree_to_the": "Я согласен с",
  "terms_of_service": "Условиями обслуживания",
  "and": "и",
  "privacy_policy": "Политикой конфиденциальности",
  "create_account": "Создать аккаунт",
  "already_have_account": "Уже есть аккаунт?",
  "login_here": "Войти здесь",
  "discover_egypt": "Откройте Египет",
  "book_amazing_activities": "Забронируйте удивительные мероприятия и впечатления",
  "scan_qr_code": "Сканировать QR-код",
  "search_activities": "Поиск мероприятий...",
  "popular_activities": "Популярные мероприятия",
  "special_events": "Специальные события",
  "additional_services": "Дополнительные услуги",
  "luxor_temple_tour": "Экскурсия по храму Луксора",
  "hours": "часов",
  "per_person": "/человек",
  "book": "Забронировать",
  "book_now": "Забронировать сейчас",
  "healthcare": "Здравоохранение",
  "medical_support": "Медицинская поддержка 24/7",
  "spa_massage": "Спа и массаж",
  "relaxation_services": "Услуги релаксации",
  "request_service": "Запросить услугу",
  "christmas_beach_party": "Рождественская пляжная вечеринка",
  "new_year_gala_dinner": "Новогодний гала-ужин",
  "special_event": "Специальное событие",
  "december": "Декабрь",
  "cultural": "Культурный",
  "language_english": "English",
  "language_arabic": "العربية",
  "language_german": "Deutsch",
  "language_spanish": "Español",
  "language_french": "Français",
  "language_italian": "Italiano",
  "language_russian": "Русский",
  "home": "Главная",
  "excursions": "Экскурсии",
  "events": "События",
  "services": "Услуги",
  "favorites": "Избранное",
  "search_placeholder": "Поиск экскурсий, событий...",
  "all": "Все",
  "snorkeling": "Снорклинг",
  "diving": "Дайвинг",
  "safari": "Сафари",
  "adventure": "Приключения",
  "view_all": "Все",
  "trending_excursions": "Популярные",
  "upcoming_events": "Предстоящие",
  "quick_services": "Быстрые услуги",
  "connect": "Связаться",
  "available": "Доступно",
  "explore_excursions": "Обзор экскурсий",
  "my_favorites": "Мое избранное",
  "no_favorites_yet": "Нет избранного",
  "start_adding_favorites": "Добавьте в избранное!",
  "favorite_excursions": "Любимые экскурсии",
  "favorite_events": "Любимые события",
  "connect_with_representative": "Связаться с представителем",
  "scan_qr_description": "Сканируйте QR для начала",
  "close": "Закрыть",
  "select_date": "Дата",
  "preferred_time": "Время",
  "number_of_people": "Человек",
  "additional_notes": "Заметки",
  "additional_notes_placeholder": "Особые пожелания...",
  "price_summary": "Цена",
  "service_fee": "Сбор",
  "total": "Итого",
  "cancel": "Отмена",
  "confirm_booking": "Подтвердить",
  "people": "чел.",
  "person": "чел.",
  "preferred_date": "Желаемая дата",
  "urgency_level": "Срочность",
  "normal": "Обычно",
  "urgent": "Срочно",
  "emergency": "Экстренно",
  "additional_details": "Детали",
  "additional_details_placeholder": "Опишите ваши потребности...",
  "service_request_info": "Свяжемся через 30 мин",
  "submit_request": "Отправить",
  "booking_confirmed": "Подтверждено!",
  "service_requested": "Отправлено!",
  "night_life": "Ночная жизнь",
  "christmas": "Рождество",
  "new_year": "Новый год",
  "select_time": "Время",
  "excursion_red_sea_name": "Снорклинг в Красном море",
  "excursion_red_sea_desc": "Исследуйте красивые коралловые рифы и красочную морскую жизнь",
  "excursion_safari_name": "Сафари в пустыне",
  "excursion_safari_desc": "Захватывающее приключение в пустыне на квадроциклах и верблюдах",
  "excursion_scuba_name": "Профессиональный дайвинг",
  "excursion_scuba_desc": "Глубоководное погружение с сертифицированными инструкторами",
  "excursion_luxor_name": "Тур в Луксорский храм",
  "excursion_luxor_desc": "Посетите древние египетские храмы и памятники",
  "excursion_bedouin_name": "Ночное сафари бедуинов",
  "excursion_bedouin_desc": "Познакомьтесь с культурой бедуинов за ужином и наблюдением за звездами",
  "excursion_parasailing_name": "Парасейлинг",
  "excursion_parasailing_desc": "Парите над Красным морем с захватывающими видами",
  "event_christmas_party_name": "Рождественская пляжная вечеринка",
  "event_christmas_party_desc": "Отпразднуйте Рождество на пляже с музыкой и едой",
  "event_new_year_gala_name": "Новогодний гала-вечер",
  "event_new_year_gala_desc": "Встречайте Новый год грандиозным праздником",
  "event_night_club_name": "Ночной клуб",
  "event_night_club_desc": "Премиальный ночной клуб с международными диджеями",
  "event_cultural_night_name": "Египетская культурная ночь",
  "event_cultural_night_desc": "Традиционная египетская музыка, танцы и кухня",
  "service_healthcare_name": "Здравоохранение",
  "service_healthcare_desc": "Круглосуточная медицинская поддержка",
  "service_spa_name": "Спа и массаж",
  "service_spa_desc": "Услуги релаксации",
  "service_doctor_name": "Консультация врача",
  "service_doctor_desc": "Онлайн и лично",
  "service_transfer_name": "Трансфер из аэропорта",
  "service_transfer_desc": "Частный транспорт",
  "service_trainer_name": "Персональный тренер",
  "service_trainer_desc": "Фитнес и здоровье",
  "service_guide_name": "Туристический гид",
  "service_guide_desc": "Частные туры",
  "upcoming_bookings": "Предстоящие бронирования",
  "my_bookings": "Мои бронирования",
  "days_until": "дней до",
  "today": "Сегодня",
  "tomorrow": "Завтра",
  "cancel_booking": "Отменить",
  "no_upcoming_bookings": "Нет предстоящих бронирований",
  "booking_cancelled": "Бронирование успешно отменено",
  "confirm": "Подтвердить",
  "offers": "Предложения",
  "real_estate": "Недвижимость",
  "shaleeh": "Шале",
  "studio": "Студия",
  "department": "Квартира",
  "villa": "Вилла",
  "select_city": "Выберите город",
  "onboarding_title_1": "Исследуйте мир",
  "onboarding_subtitle_1": "Откройте для себя скрытые жемчужины и захватывающие дух места, созданные специально для вас.",
  "onboarding_title_2": "Роскошный отдых",
  "onboarding_subtitle_2": "Ощутите гостеприимство мирового уровня в тщательно отобранных отелях и уникальных местах проживания.",
  "onboarding_title_3": "Путешествие без усилий",
  "onboarding_subtitle_3": "С легкостью планируйте и бронируйте всю поездку: от авиабилетов до местных туров.",
  "get_started": "Начать",
  "skip": "Пропустить"
};
static const Map<String,dynamic> _pl = {
  "hello": "Cześć",
  "choose_image": "Wybierz zdjęcie",
  "take_photo": "Zrób zdjęcie",
  "choose_from_gallery": "Wybierz z galerii",
  "back_to_role_selection": "Powrót do wyboru roli",
  "login_as_customer": "Zaloguj się jako klient",
  "enter_credentials_to_continue": "Wprowadź dane, aby kontynuować",
  "continue_with_google": "Kontynuuj z Google",
  "continue_with_apple": "Kontynuuj z Apple",
  "or_continue_with_email": "Lub kontynuuj przez e-mail",
  "email_address": "Adres e-mail",
  "email_placeholder": "ty@przyklad.com",
  "email_required": "Adres e-mail jest wymagany",
  "email_invalid": "Nieprawidłowy adres e-mail",
  "phone_number_required": "Numer telefonu jest wymagany",
  "phone_number_invalid": "Nieprawidłowy numer telefonu",
  "search_country": "Wyszukaj kraj",
  "otp_title": "Kod weryfikacyjny",
  "otp_subtitle": "Wysłaliśmy kod weryfikacyjny na Twój numer telefonu",
  "verify": "Zweryfikuj",
  "resend_code": "Wyślij kod ponownie",
  "didnt_receive_code": "Nie otrzymałeś kodu?",
  "otp_invalid": "Nieprawidłowy kod OTP",
  "password": "Hasło",
  "password_placeholder": "••••••••",
  "password_required": "Hasło jest wymagane",
  "password_length_error": "Hasło musi mieć co najmniej 6 znaków",
  "remember_me": "Zapamiętaj mnie",
  "forgot_password": "Nie pamiętasz hasła?",
  "login": "Zaloguj się",
  "dont_have_account": "Nie masz konta?",
  "register_now": "Zarejestruj się teraz",
  "language_english": "English",
  "language_arabic": "العربية",
  "language_german": "Deutsch",
  "language_spanish": "Español",
  "language_french": "Français",
  "language_italian": "Italiano",
  "language_russian": "Русский",
  "register_as_customer": "Zarejestruj się jako klient",
  "create_account_to_get_started": "Utwórz konto, aby rozpocząć",
  "or_register_with_email": "Lub zarejestruj się przez e-mail",
  "full_name": "Imię i nazwisko",
  "full_name_placeholder": "Jan Kowalski",
  "phone_number": "Numer telefonu",
  "phone_placeholder": "+48 123 456 789",
  "confirm_password": "Potwierdź hasło",
  "confirm_password_placeholder": "••••••••",
  "i_agree_to_the": "Zgadzam się z",
  "terms_of_service": "Warunkami korzystania",
  "and": "i",
  "privacy_policy": "Polityką prywatności",
  "create_account": "Utwórz konto",
  "already_have_account": "Masz już konto?",
  "login_here": "Zaloguj się tutaj",
  "discover_egypt": "Odkryj Egipt",
  "book_amazing_activities": "Rezerwuj niesamowite atrakcje i przeżycia",
  "scan_qr_code": "Zeskanuj kod QR",
  "search_activities": "Szukaj atrakcji...",
  "popular_activities": "Popularne atrakcje",
  "special_events": "Wydarzenia specjalne",
  "additional_services": "Usługi dodatkowe",
  "luxor_temple_tour": "Wycieczka do Świątyni w Luksorze",
  "hours": "godz.",
  "per_person": "/osobę",
  "book": "Rezerwuj",
  "book_now": "Rezerwuj teraz",
  "healthcare": "Opieka zdrowotna",
  "medical_support": "Wsparcie medyczne 24/7",
  "spa_massage": "Spa i masaż",
  "relaxation_services": "Usługi relaksacyjne",
  "request_service": "Zamów usługę",
  "christmas_beach_party": "Świąteczna impreza na plaży",
  "new_year_gala_dinner": "Sylwestrowa kolacja galowa",
  "special_event": "Wydarzenie specjalne",
  "december": "Grudzień",
  "cultural": "Kulturalne",
  "home": "Strona główna",
  "excursions": "Wycieczki",
  "events": "Wydarzenia",
  "services": "Usługi",
  "favorites": "Ulubione",
  "search_placeholder": "Szukaj wycieczek, wydarzeń...",
  "all": "Wszystkie",
  "snorkeling": "Nurkowanie z rurką",
  "diving": "Nurkowanie",
  "safari": "Safari",
  "adventure": "Przygoda",
  "view_all": "Pokaż wszystko",
  "trending_excursions": "Popularne wycieczki",
  "upcoming_events": "Nadchodzące wydarzenia",
  "quick_services": "Szybkie usługi",
  "connect": "Kontakt",
  "available": "Dostępne",
  "explore_excursions": "Przeglądaj wycieczki",
  "my_favorites": "Moje ulubione",
  "no_favorites_yet": "Brak ulubionych",
  "start_adding_favorites": "Zacznij dodawać wycieczki do ulubionych!",
  "favorite_excursions": "Ulubione wycieczki",
  "favorite_events": "Ulubione wydarzenia",
  "connect_with_representative": "Połącz z przedstawicielem",
  "scan_qr_description": "Zeskanuj kod QR przedstawiciela, aby rozpocząć",
  "close": "Zamknij",
  "select_date": "Wybierz datę",
  "preferred_time": "Preferowana godzina",
  "number_of_people": "Liczba osób",
  "additional_notes": "Dodatkowe uwagi",
  "additional_notes_placeholder": "Specjalne życzenia lub wymagania...",
  "price_summary": "Podsumowanie ceny",
  "service_fee": "Opłata serwisowa",
  "total": "Razem",
  "cancel": "Anuluj",
  "confirm_booking": "Potwierdź rezerwację",
  "people": "osoby",
  "person": "osoba",
  "preferred_date": "Preferowana data",
  "urgency_level": "Poziom pilności",
  "normal": "Normalny",
  "urgent": "Pilny",
  "emergency": "Nagły wypadek",
  "additional_details": "Dodatkowe szczegóły",
  "additional_details_placeholder": "Opisz swoje potrzeby...",
  "service_request_info": "Skontaktujemy się z Tobą w ciągu 30 minut",
  "submit_request": "Wyślij zgłoszenie",
  "booking_confirmed": "Rezerwacja potwierdzona!",
  "service_requested": "Zgłoszenie wysłane!",
  "night_life": "Życie nocne",
  "christmas": "Boże Narodzenie",
  "new_year": "Nowy Rok",
  "select_time": "Wybierz godzinę",
  "excursion_red_sea_name": "Snorkeling w Morzu Czerwonym",
  "excursion_red_sea_desc": "Odkryj piękne rafy koralowe i kolorowe życie morskie",
  "excursion_safari_name": "Pustynne Safari",
  "excursion_safari_desc": "Ekscytująca przygoda na quadach i wielbłądach",
  "excursion_scuba_name": "Profesjonalne nurkowanie",
  "excursion_scuba_desc": "Głębinowe nurkowanie z certyfikowanymi instruktorami",
  "excursion_luxor_name": "Wycieczka do Luksoru",
  "excursion_luxor_desc": "Odwiedź starożytne egipskie świątynie i zabytki",
  "excursion_bedouin_name": "Beduinska noc",
  "excursion_bedouin_desc": "Poznaj kulturę Beduinów przy kolacji i obserwacji gwiazd",
  "excursion_parasailing_name": "Parasailing",
  "excursion_parasailing_desc": "Szybuj nad Morzem Czerwonym z zapierającymi dech widokami",
  "event_christmas_party_name": "Świąteczna impreza plażowa",
  "event_christmas_party_desc": "Świętuj Boże Narodzenie na plaży z muzyką i jedzeniem",
  "event_new_year_gala_name": "Gala Sylwestrowa",
  "event_new_year_gala_desc": "Powitaj Nowy Rok spektakularną zabawą",
  "event_night_club_name": "Noc w klubie",
  "event_night_club_desc": "Impreza w klubie premium z międzynarodowymi DJ-ami",
  "event_cultural_night_name": "Egipska noc kulturalna",
  "event_cultural_night_desc": "Tradycyjna egipska muzyka, taniec i kuchnia",
  "service_healthcare_name": "Opieka zdrowotna",
  "service_healthcare_desc": "Wsparcie medyczne 24/7",
  "service_spa_name": "Spa i masaż",
  "service_spa_desc": "Usługi relaksacyjne",
  "service_doctor_name": "Konsultacja lekarska",
  "service_doctor_desc": "Online i stacjonarnie",
  "service_transfer_name": "Transfer lotniskowy",
  "service_transfer_desc": "Transport prywatny",
  "service_trainer_name": "Trener personalny",
  "service_trainer_desc": "Fitness i zdrowie",
  "service_guide_name": "Przewodnik turystyczny",
  "service_guide_desc": "Prywatne wycieczki",
  "upcoming_bookings": "Nadchodzące rezerwacje",
  "my_bookings": "Moje rezerwacje",
  "days_until": "dni do",
  "today": "Dzisiaj",
  "tomorrow": "Jutro",
  "cancel_booking": "Anuluj",
  "no_upcoming_bookings": "Brak nadchodzących rezerwacji",
  "booking_cancelled": "Rezerwacja anulowana pomyślnie",
  "confirm": "Potwierdź",
  "offers": "Oferty",
  "real_estate": "Nieruchomości",
  "shaleeh": "Domek",
  "studio": "Studio",
  "department": "Mieszkanie",
  "villa": "Willa",
  "select_city": "Wybierz miasto",
  "onboarding_title_1": "Odkrywaj świat",
  "onboarding_subtitle_1": "Odkryj ukryte skarby i zapierające dech w piersiach kierunki, skrojone idealnie dla Ciebie.",
  "onboarding_title_2": "Luksusowe pobyty",
  "onboarding_subtitle_2": "Doświadcz światowej klasy gościnności w starannie dobranych hotelach i unikalnych miejscach.",
  "onboarding_title_3": "Podróż bez wysiłku",
  "onboarding_subtitle_3": "Z łatwością planuj i rezerwuj całą podróż, od lotów po lokalne wycieczki.",
  "get_started": "Zacznij",
  "skip": "Pomiń"
};
static const Map<String,dynamic> _en = {
  "hello": "Hello",
  "choose_image": "Choose Image",
  "take_photo": "Take Photo",
  "choose_from_gallery": "Choose from Gallery",
  "back_to_role_selection": "Back to role selection",
  "login_as_customer": "Login as Customer",
  "enter_credentials_to_continue": "Enter your credentials to continue",
  "continue_with_google": "Continue with Google",
  "continue_with_apple": "Continue with Apple",
  "or_continue_with_email": "Or continue with email",
  "email_address": "Email Address",
  "email_placeholder": "you@example.com",
  "email_required": "Email is required",
  "email_invalid": "Invalid email address",
  "phone_number_required": "Phone number is required",
  "phone_number_invalid": "Invalid phone number",
  "search_country": "Search Country",
  "otp_title": "Verification Code",
  "otp_subtitle": "We have sent a verification code to your phone number",
  "verify": "Verify",
  "resend_code": "Resend Code",
  "didnt_receive_code": "Didn't receive the code?",
  "otp_invalid": "Invalid OTP code",
  "password": "Password",
  "password_placeholder": "••••••••",
  "password_required": "Password is required",
  "password_length_error": "Password must be at least 6 characters",
  "remember_me": "Remember me",
  "forgot_password": "Forgot password?",
  "login": "Login",
  "dont_have_account": "Don't have an account?",
  "register_now": "Register Now",
  "language_english": "English",
  "language_arabic": "العربية",
  "language_german": "Deutsch",
  "language_spanish": "Español",
  "language_french": "Français",
  "language_italian": "Italiano",
  "language_russian": "Русский",
  "register_as_customer": "Register as Customer",
  "create_account_to_get_started": "Create your account to get started",
  "or_register_with_email": "Or register with email",
  "full_name": "Full Name",
  "full_name_placeholder": "John Doe",
  "phone_number": "Phone Number",
  "phone_placeholder": "+20 123 456 7890",
  "confirm_password": "Confirm Password",
  "confirm_password_placeholder": "••••••••",
  "i_agree_to_the": "I agree to the",
  "terms_of_service": "Terms of Service",
  "and": "and",
  "privacy_policy": "Privacy Policy",
  "create_account": "Create Account",
  "already_have_account": "Already have an account?",
  "login_here": "Login Here",
  "discover_egypt": "Discover Egypt",
  "book_amazing_activities": "Book amazing activities and experiences",
  "scan_qr_code": "Scan QR Code",
  "search_activities": "Search activities...",
  "popular_activities": "Popular Activities",
  "special_events": "Special Events",
  "additional_services": "Additional Services",
  "luxor_temple_tour": "Luxor Temple Tour",
  "hours": "hours",
  "per_person": "/person",
  "book": "Book",
  "book_now": "Book Now",
  "healthcare": "Healthcare",
  "medical_support": "24/7 Medical Support",
  "spa_massage": "Spa & Massage",
  "relaxation_services": "Relaxation Services",
  "request_service": "Request Service",
  "christmas_beach_party": "Christmas Beach Party",
  "new_year_gala_dinner": "New Year Gala Dinner",
  "special_event": "Special Event",
  "december": "December",
  "cultural": "Cultural",
  "home": "Home",
  "excursions": "Excursions",
  "events": "Events",
  "services": "Services",
  "favorites": "Favorites",
  "search_placeholder": "Search excursions, events, or services...",
  "all": "All",
  "snorkeling": "Snorkeling",
  "diving": "Diving",
  "safari": "Safari",
  "adventure": "Adventure",
  "view_all": "View All",
  "trending_excursions": "Trending Excursions",
  "upcoming_events": "Upcoming Events",
  "quick_services": "Quick Services",
  "connect": "Connect",
  "available": "Available",
  "explore_excursions": "Explore Excursions",
  "my_favorites": "My Favorites",
  "no_favorites_yet": "No favorites yet",
  "start_adding_favorites": "Start adding excursions and events to your favorites!",
  "favorite_excursions": "Favorite Excursions",
  "favorite_events": "Favorite Events",
  "connect_with_representative": "Connect with Representative",
  "scan_qr_description": "Scan your representative's QR code to get started",
  "close": "Close",
  "select_date": "Select Date",
  "preferred_time": "Preferred Time",
  "number_of_people": "Number of People",
  "additional_notes": "Additional Notes",
  "additional_notes_placeholder": "Any special requests or requirements...",
  "price_summary": "Price Summary",
  "service_fee": "Service Fee",
  "total": "Total",
  "cancel": "Cancel",
  "confirm_booking": "Confirm Booking",
  "people": "people",
  "person": "person",
  "preferred_date": "Preferred Date",
  "urgency_level": "Urgency Level",
  "normal": "Normal",
  "urgent": "Urgent",
  "emergency": "Emergency",
  "additional_details": "Additional Details",
  "additional_details_placeholder": "Please describe your needs or any specific requirements...",
  "service_request_info": "Our team will contact you within 30 minutes to confirm your service request",
  "submit_request": "Submit Request",
  "booking_confirmed": "Booking Confirmed!",
  "service_requested": "Service Request Submitted!",
  "night_life": "Night Life",
  "christmas": "Christmas",
  "new_year": "New Year",
  "select_time": "Select time",
  "excursion_red_sea_name": "Red Sea Snorkeling Adventure",
  "excursion_red_sea_desc": "Explore the beautiful coral reefs and colorful marine life",
  "excursion_safari_name": "Desert Safari Experience",
  "excursion_safari_desc": "Thrilling desert adventure with quad bikes and camel rides",
  "excursion_scuba_name": "Professional Scuba Diving",
  "excursion_scuba_desc": "Deep sea diving experience with certified instructors",
  "excursion_luxor_name": "Luxor Temple Tour",
  "excursion_luxor_desc": "Visit ancient Egyptian temples and monuments",
  "excursion_bedouin_name": "Bedouin Night Safari",
  "excursion_bedouin_desc": "Experience Bedouin culture with dinner and stargazing",
  "excursion_parasailing_name": "Parasailing Adventure",
  "excursion_parasailing_desc": "Soar above the Red Sea with breathtaking views",
  "event_christmas_party_name": "Christmas Beach Party",
  "event_christmas_party_desc": "Celebrate Christmas on the beach with music and food",
  "event_new_year_gala_name": "New Year Gala Night",
  "event_new_year_gala_desc": "Ring in the new year with a spectacular celebration",
  "event_night_club_name": "Night Club Experience",
  "event_night_club_desc": "Premium nightclub experience with international DJs",
  "event_cultural_night_name": "Egyptian Cultural Night",
  "event_cultural_night_desc": "Traditional Egyptian music, dance, and cuisine",
  "service_healthcare_name": "Healthcare",
  "service_healthcare_desc": "24/7 Medical Support",
  "service_spa_name": "Spa & Massage",
  "service_spa_desc": "Relaxation Services",
  "service_doctor_name": "Doctor Consultation",
  "service_doctor_desc": "Online & In-person",
  "service_transfer_name": "Airport Transfer",
  "service_transfer_desc": "Private Transportation",
  "service_trainer_name": "Personal Trainer",
  "service_trainer_desc": "Fitness & Wellness",
  "service_guide_name": "Tour Guide",
  "service_guide_desc": "Private Tours",
  "upcoming_bookings": "Upcoming Bookings",
  "my_bookings": "My Bookings",
  "days_until": "days until",
  "today": "Today",
  "tomorrow": "Tomorrow",
  "cancel_booking": "Cancel",
  "no_upcoming_bookings": "No upcoming bookings",
  "booking_cancelled": "Booking cancelled successfully",
  "confirm": "Confirm",
  "offers": "Offers",
  "real_estate": "Real Estate",
  "shaleeh": "Shaleeh",
  "studio": "Studio",
  "department": "Department",
  "villa": "Villa",
  "select_city": "Select City",
  "onboarding_title_1": "Explore the World",
  "onboarding_subtitle_1": "Discover hidden gems and breathtaking destinations tailored just for you.",
  "onboarding_title_2": "Luxury Stays",
  "onboarding_subtitle_2": "Experience world-class hospitality in handpicked hotels and unique stays.",
  "onboarding_title_3": "Effortless Travel",
  "onboarding_subtitle_3": "Plan and book your entire trip with ease, from flights to local tours.",
  "get_started": "Get Started",
  "skip": "Skip"
};
static const Map<String,dynamic> _it = {
  "hello": "Ciao",
  "choose_image": "Scegli immagine",
  "take_photo": "Scatta foto",
  "choose_from_gallery": "Scegli dalla galleria",
  "back_to_role_selection": "Torna alla selezione del ruolo",
  "login_as_customer": "Accedi come cliente",
  "enter_credentials_to_continue": "Inserisci le tue credenziali per continuare",
  "continue_with_google": "Continua con Google",
  "continue_with_apple": "Continua con Apple",
  "or_continue_with_email": "O continua con l'email",
  "email_address": "Indirizzo email",
  "email_placeholder": "you@example.com",
  "email_required": "Email richiesta",
  "email_invalid": "Indirizzo email non valido",
  "phone_number_required": "Numero di telefono richiesto",
  "phone_number_invalid": "Numero di telefono non valido",
  "search_country": "Cerca paese",
  "otp_title": "Codice di verifica",
  "otp_subtitle": "Abbiamo inviato un codice di verifica al tuo numero di telefono",
  "verify": "Verifica",
  "resend_code": "Rinvia codice",
  "didnt_receive_code": "Non hai ricevuto il codice?",
  "otp_invalid": "Codice OTP non valido",
  "password": "Password",
  "password_placeholder": "••••••••",
  "password_required": "Password richiesta",
  "password_length_error": "La password deve contenere almeno 6 caratteri",
  "remember_me": "Ricordami",
  "forgot_password": "Password dimenticata?",
  "login": "Accedi",
  "dont_have_account": "Non hai un account?",
  "register_now": "Registrati ora",
  "register_as_customer": "Registrati come cliente",
  "create_account_to_get_started": "Crea il tuo account per iniziare",
  "or_register_with_email": "O registrati con l'email",
  "full_name": "Nome completo",
  "full_name_placeholder": "Mario Rossi",
  "phone_number": "Numero di telefono",
  "phone_placeholder": "+39 123 456 7890",
  "confirm_password": "Conferma password",
  "confirm_password_placeholder": "••••••••",
  "i_agree_to_the": "Accetto i",
  "terms_of_service": "Termini di Servizio",
  "and": "e",
  "privacy_policy": "Informativa sulla Privacy",
  "create_account": "Crea account",
  "already_have_account": "Hai già un account?",
  "login_here": "Accedi qui",
  "discover_egypt": "Scopri l'Egitto",
  "book_amazing_activities": "Prenota attività ed esperienze incredibili",
  "scan_qr_code": "Scansiona codice QR",
  "search_activities": "Cerca attività...",
  "popular_activities": "Attività popolari",
  "special_events": "Eventi speciali",
  "additional_services": "Servizi aggiuntivi",
  "luxor_temple_tour": "Tour del Tempio di Luxor",
  "hours": "ore",
  "per_person": "/persona",
  "book": "Prenota",
  "book_now": "Prenota ora",
  "healthcare": "Assistenza sanitaria",
  "medical_support": "Supporto medico 24/7",
  "spa_massage": "Spa e massaggi",
  "relaxation_services": "Servizi di rilassamento",
  "request_service": "Richiedi servizio",
  "christmas_beach_party": "Festa di Natale in spiaggia",
  "new_year_gala_dinner": "Cena di gala di Capodanno",
  "special_event": "Evento speciale",
  "december": "Dicembre",
  "cultural": "Culturale",
  "language_english": "English",
  "language_arabic": "العربية",
  "language_german": "Deutsch",
  "language_spanish": "Español",
  "language_french": "Français",
  "language_italian": "Italiano",
  "language_russian": "Русский",
  "home": "Home",
  "excursions": "Escursioni",
  "events": "Eventi",
  "services": "Servizi",
  "favorites": "Preferiti",
  "search_placeholder": "Cerca escursioni, eventi...",
  "all": "Tutti",
  "snorkeling": "Snorkeling",
  "diving": "Immersioni",
  "safari": "Safari",
  "adventure": "Avventura",
  "view_all": "Vedi tutto",
  "trending_excursions": "Di tendenza",
  "upcoming_events": "Prossimi eventi",
  "quick_services": "Servizi rapidi",
  "connect": "Connetti",
  "available": "Disponibile",
  "explore_excursions": "Esplora escursioni",
  "my_favorites": "I miei preferiti",
  "no_favorites_yet": "Nessun preferito",
  "start_adding_favorites": "Aggiungi ai preferiti!",
  "favorite_excursions": "Escursioni preferite",
  "favorite_events": "Eventi preferiti",
  "connect_with_representative": "Contatta rappresentante",
  "scan_qr_description": "Scansiona QR per iniziare",
  "close": "Chiudi",
  "select_date": "Data",
  "preferred_time": "Ora",
  "number_of_people": "Persone",
  "additional_notes": "Note",
  "additional_notes_placeholder": "Richieste speciali...",
  "price_summary": "Prezzo",
  "service_fee": "Commissione",
  "total": "Totale",
  "cancel": "Annulla",
  "confirm_booking": "Conferma",
  "people": "persone",
  "person": "persona",
  "preferred_date": "Data preferita",
  "urgency_level": "Urgenza",
  "normal": "Normale",
  "urgent": "Urgente",
  "emergency": "Emergenza",
  "additional_details": "Dettagli",
  "additional_details_placeholder": "Descrivi le tue esigenze...",
  "service_request_info": "Ti contatteremo in 30 min",
  "submit_request": "Invia",
  "booking_confirmed": "Confermato!",
  "service_requested": "Inviato!",
  "night_life": "Vita notturna",
  "christmas": "Natale",
  "new_year": "Capodanno",
  "select_time": "Ora",
  "excursion_red_sea_name": "Avventura di Snorkeling nel Mar Rosso",
  "excursion_red_sea_desc": "Esplora le bellissime barriere coralline e la colorata vita marina",
  "excursion_safari_name": "Esperienza Safari nel Deserto",
  "excursion_safari_desc": "Emozionante avventura nel deserto con quad e giri in cammello",
  "excursion_scuba_name": "Immersioni Subacquee Professionali",
  "excursion_scuba_desc": "Esperienza di immersione in acque profonde con istruttori certificati",
  "excursion_luxor_name": "Tour del Tempio di Luxor",
  "excursion_luxor_desc": "Visita antichi templi e monumenti egizi",
  "excursion_bedouin_name": "Safari Notturno Beduino",
  "excursion_bedouin_desc": "Vivi la cultura beduina con cena e osservazione delle stelle",
  "excursion_parasailing_name": "Avventura di Parasailing",
  "excursion_parasailing_desc": "Vola sopra il Mar Rosso con viste mozzafiato",
  "event_christmas_party_name": "Festa di Natale in Spiaggia",
  "event_christmas_party_desc": "Festeggia il Natale in spiaggia con musica e cibo",
  "event_new_year_gala_name": "Serata di Gala di Capodanno",
  "event_new_year_gala_desc": "Accogli il nuovo anno con una celebrazione spettacolare",
  "event_night_club_name": "Esperienza Night Club",
  "event_night_club_desc": "Esperienza premium in discoteca con DJ internazionali",
  "event_cultural_night_name": "Notte Culturale Egiziana",
  "event_cultural_night_desc": "Musica, danza e cucina tradizionale egiziana",
  "service_healthcare_name": "Assistenza Sanitaria",
  "service_healthcare_desc": "Supporto medico 24/7",
  "service_spa_name": "Spa e Massaggi",
  "service_spa_desc": "Servizi di relax",
  "service_doctor_name": "Consulto Medico",
  "service_doctor_desc": "Online e di persona",
  "service_transfer_name": "Trasferimento Aeroportuale",
  "service_transfer_desc": "Trasporto privato",
  "service_trainer_name": "Personal Trainer",
  "service_trainer_desc": "Fitness e benessere",
  "service_guide_name": "Guida Turistica",
  "service_guide_desc": "Tour privati",
  "upcoming_bookings": "Prenotazioni imminenti",
  "my_bookings": "Le mie prenotazioni",
  "days_until": "giorni a",
  "today": "Oggi",
  "tomorrow": "Domani",
  "cancel_booking": "Annulla",
  "no_upcoming_bookings": "Nessuna prenotazione imminente",
  "booking_cancelled": "Prenotazione annullata con successo",
  "confirm": "Conferma",
  "offers": "Offerte",
  "real_estate": "Immobiliare",
  "shaleeh": "Chalet",
  "studio": "Studio",
  "department": "Appartamento",
  "villa": "Villa",
  "select_city": "Seleziona città",
  "onboarding_title_1": "Esplora il mondo",
  "onboarding_subtitle_1": "Scopri gemme nascoste e destinazioni mozzafiato su misura per te.",
  "onboarding_title_2": "Soggiorni di lusso",
  "onboarding_subtitle_2": "Sperimenta un'ospitalità di classe mondiale in hotel selezionati e soggiorni unici.",
  "onboarding_title_3": "Viaggio senza sforzo",
  "onboarding_subtitle_3": "Pianifica e prenota l'intero viaggio con facilità, dai voli ai tour locali.",
  "get_started": "Iniziare",
  "skip": "Saltare"
};
static const Map<String,dynamic> _fr = {
  "hello": "Bonjour",
  "choose_image": "Choisir une image",
  "take_photo": "Prendre une photo",
  "choose_from_gallery": "Choisir dans la galerie",
  "back_to_role_selection": "Retour à la sélection de rôle",
  "login_as_customer": "Se connecter en tant que client",
  "enter_credentials_to_continue": "Entrez vos identifiants pour continuer",
  "continue_with_google": "Continuer avec Google",
  "continue_with_apple": "Continuer avec Apple",
  "or_continue_with_email": "Ou continuer avec l'e-mail",
  "email_address": "Adresse e-mail",
  "email_placeholder": "you@example.com",
  "email_required": "E-mail requis",
  "email_invalid": "Adresse e-mail invalide",
  "phone_number_required": "Numéro de téléphone requis",
  "phone_number_invalid": "Numéro de téléphone invalide",
  "search_country": "Rechercher un pays",
  "otp_title": "Code de vérification",
  "otp_subtitle": "Nous avons envoyé un code de vérification à votre numéro de téléphone",
  "verify": "Vérifier",
  "resend_code": "Renvoyer le code",
  "didnt_receive_code": "Vous n'avez pas reçu le code ?",
  "otp_invalid": "Code OTP invalide",
  "password": "Mot de passe",
  "password_placeholder": "••••••••",
  "password_required": "Mot de passe requis",
  "password_length_error": "Le mot de passe doit contenir au moins 6 caractères",
  "remember_me": "Se souvenir de moi",
  "forgot_password": "Mot de passe oublié ?",
  "login": "Se connecter",
  "dont_have_account": "Vous n'avez pas de compte ?",
  "register_now": "S'inscrire maintenant",
  "register_as_customer": "S'inscrire en tant que client",
  "create_account_to_get_started": "Créez votre compte pour commencer",
  "or_register_with_email": "Ou s'inscrire avec l'e-mail",
  "full_name": "Nom complet",
  "full_name_placeholder": "Jean Dupont",
  "phone_number": "Numéro de téléphone",
  "phone_placeholder": "+33 1 23 45 67 89",
  "confirm_password": "Confirmer le mot de passe",
  "confirm_password_placeholder": "••••••••",
  "i_agree_to_the": "J'accepte les",
  "terms_of_service": "Conditions de Service",
  "and": "et",
  "privacy_policy": "Politique de Confidentialité",
  "create_account": "Créer un compte",
  "already_have_account": "Vous avez déjà un compte ?",
  "login_here": "Connectez-vous ici",
  "discover_egypt": "Découvrir l'Égypte",
  "book_amazing_activities": "Réservez des activités et expériences incroyables",
  "scan_qr_code": "Scanner le code QR",
  "search_activities": "Rechercher des activités...",
  "popular_activities": "Activités populaires",
  "special_events": "Événements spéciaux",
  "additional_services": "Services supplémentaires",
  "luxor_temple_tour": "Visite du temple de Louxor",
  "hours": "heures",
  "per_person": "/personne",
  "book": "Réserver",
  "book_now": "Réserver maintenant",
  "healthcare": "Soins de santé",
  "medical_support": "Support médical 24/7",
  "spa_massage": "Spa et massage",
  "relaxation_services": "Services de relaxation",
  "request_service": "Demander un service",
  "christmas_beach_party": "Fête de Noël sur la plage",
  "new_year_gala_dinner": "Dîner de gala du Nouvel An",
  "special_event": "Événement spécial",
  "december": "Décembre",
  "cultural": "Culturel",
  "language_english": "English",
  "language_arabic": "العربية",
  "language_german": "Deutsch",
  "language_spanish": "Español",
  "language_french": "Français",
  "language_italian": "Italiano",
  "language_russian": "Русский",
  "home": "Accueil",
  "excursions": "Excursions",
  "events": "Événements",
  "services": "Services",
  "favorites": "Favoris",
  "search_placeholder": "Rechercher excursions, événements...",
  "all": "Tout",
  "snorkeling": "Plongée",
  "diving": "Plongée sous-marine",
  "safari": "Safari",
  "adventure": "Aventure",
  "view_all": "Voir tout",
  "trending_excursions": "Excursions populaires",
  "upcoming_events": "Événements à venir",
  "quick_services": "Services rapides",
  "connect": "Connecter",
  "available": "Disponible",
  "explore_excursions": "Explorer les excursions",
  "my_favorites": "Mes favoris",
  "no_favorites_yet": "Pas encore de favoris",
  "start_adding_favorites": "Commencez à ajouter des favoris !",
  "favorite_excursions": "Excursions favorites",
  "favorite_events": "Événements favoris",
  "connect_with_representative": "Contacter un représentant",
  "scan_qr_description": "Scannez le code QR pour commencer",
  "close": "Fermer",
  "select_date": "Date",
  "preferred_time": "Heure",
  "number_of_people": "Personnes",
  "additional_notes": "Notes",
  "additional_notes_placeholder": "Demandes spéciales...",
  "price_summary": "Prix",
  "service_fee": "Frais",
  "total": "Total",
  "cancel": "Annuler",
  "confirm_booking": "Confirmer",
  "people": "personnes",
  "person": "personne",
  "preferred_date": "Date préférée",
  "urgency_level": "Urgence",
  "normal": "Normal",
  "urgent": "Urgent",
  "emergency": "Urgence",
  "additional_details": "Détails",
  "additional_details_placeholder": "Décrivez vos besoins...",
  "service_request_info": "Nous vous contacterons dans 30 min",
  "submit_request": "Envoyer",
  "booking_confirmed": "Confirmé !",
  "service_requested": "Envoyé !",
  "night_life": "Vie nocturne",
  "christmas": "Noël",
  "new_year": "Nouvel An",
  "select_time": "Heure",
  "excursion_red_sea_name": "Aventure de plongée en apnée en Mer Rouge",
  "excursion_red_sea_desc": "Explorez les magnifiques récifs coralliens et la vie marine colorée",
  "excursion_safari_name": "Expérience Safari dans le Désert",
  "excursion_safari_desc": "Aventure palpitante dans le désert avec quad et balade à dos de chameau",
  "excursion_scuba_name": "Plongée sous-marine professionnelle",
  "excursion_scuba_desc": "Expérience de plongée en haute mer avec des instructeurs certifiés",
  "excursion_luxor_name": "Visite du temple de Louxor",
  "excursion_luxor_desc": "Visitez les temples et monuments de l'Égypte ancienne",
  "excursion_bedouin_name": "Safari nocturne bédouin",
  "excursion_bedouin_desc": "Vivez la culture bédouine avec dîner et observation des étoiles",
  "excursion_parasailing_name": "Aventure en parachute ascensionnel",
  "excursion_parasailing_desc": "Volez au-dessus de la Mer Rouge avec des vues à couper le souffle",
  "event_christmas_party_name": "Fête de Noël sur la plage",
  "event_christmas_party_desc": "Célébrez Noël sur la plage avec musique et nourriture",
  "event_new_year_gala_name": "Soirée de Gala du Nouvel An",
  "event_new_year_gala_desc": "Fêtez la nouvelle année avec une célébration spectaculaire",
  "event_night_club_name": "Expérience Night Club",
  "event_night_club_desc": "Expérience de boîte de nuit premium avec des DJ internationaux",
  "event_cultural_night_name": "Soirée culturelle égyptienne",
  "event_cultural_night_desc": "Musique traditionnelle égyptienne, danse et cuisine",
  "service_healthcare_name": "Soins de santé",
  "service_healthcare_desc": "Assistance médicale 24/7",
  "service_spa_name": "Spa & Massage",
  "service_spa_desc": "Services de relaxation",
  "service_doctor_name": "Consultation médicale",
  "service_doctor_desc": "En ligne et en personne",
  "service_transfer_name": "Transfert aéroport",
  "service_transfer_desc": "Transport privé",
  "service_trainer_name": "Entraîneur personnel",
  "service_trainer_desc": "Fitness et bien-être",
  "service_guide_name": "Guide touristique",
  "service_guide_desc": "Visites privées",
  "upcoming_bookings": "Réservations à venir",
  "my_bookings": "Mes réservations",
  "days_until": "jours avant",
  "today": "Aujourd'hui",
  "tomorrow": "Demain",
  "cancel_booking": "Annuler",
  "no_upcoming_bookings": "Pas de réservations à venir",
  "booking_cancelled": "Réservation annulée avec succès",
  "confirm": "Confirmer",
  "offers": "Offres",
  "real_estate": "Immobilier",
  "shaleeh": "Chalet",
  "studio": "Studio",
  "department": "Appartement",
  "villa": "Villa",
  "select_city": "Sélectionner une ville",
  "onboarding_title_1": "Explorer le monde",
  "onboarding_subtitle_1": "Découvrez des joyaux cachés et des destinations à couper le souffle, conçus rien que pour vous.",
  "onboarding_title_2": "Séjours de luxe",
  "onboarding_subtitle_2": "Découvrez l'hospitalité de classe mondiale dans des hôtels triés sur le volet et des séjours uniques.",
  "onboarding_title_3": "Voyage sans effort",
  "onboarding_subtitle_3": "Planifiez et réservez l'intégralité de votre voyage en toute simplicité, des vols aux visites locales.",
  "get_started": "Commencer",
  "skip": "Passer"
};
static const Map<String,dynamic> _es = {
  "hello": "Hola",
  "choose_image": "Elegir imagen",
  "take_photo": "Tomar foto",
  "choose_from_gallery": "Elegir de la galería",
  "back_to_role_selection": "Volver a la selección de rol",
  "login_as_customer": "Iniciar sesión como cliente",
  "enter_credentials_to_continue": "Ingresa tus credenciales para continuar",
  "continue_with_google": "Continuar con Google",
  "continue_with_apple": "Continuar con Apple",
  "or_continue_with_email": "O continuar con correo electrónico",
  "email_address": "Dirección de correo electrónico",
  "email_placeholder": "you@example.com",
  "email_required": "Se requiere correo electrónico",
  "email_invalid": "Dirección de correo electrónico no válida",
  "phone_number_required": "Se requiere número de teléfono",
  "phone_number_invalid": "Número de teléfono no válido",
  "search_country": "Buscar país",
  "otp_title": "Código de verificación",
  "otp_subtitle": "Hemos enviado un código de verificación a su número de teléfono",
  "verify": "Verificar",
  "resend_code": "Reenviar código",
  "didnt_receive_code": "¿No recibiste el código?",
  "otp_invalid": "Código OTP no válido",
  "password": "Contraseña",
  "password_placeholder": "••••••••",
  "password_required": "Se requiere contraseña",
  "password_length_error": "La contraseña debe tener al menos 6 caracteres",
  "remember_me": "Recordarme",
  "forgot_password": "¿Olvidaste tu contraseña?",
  "login": "Iniciar sesión",
  "dont_have_account": "¿No tienes una cuenta?",
  "register_now": "Regístrate ahora",
  "register_as_customer": "Registrarse como cliente",
  "create_account_to_get_started": "Crea tu cuenta para comenzar",
  "or_register_with_email": "O regístrate con correo electrónico",
  "full_name": "Nombre completo",
  "full_name_placeholder": "Juan Pérez",
  "phone_number": "Número de teléfono",
  "phone_placeholder": "+34 123 456 789",
  "confirm_password": "Confirmar contraseña",
  "confirm_password_placeholder": "••••••••",
  "i_agree_to_the": "Acepto los",
  "terms_of_service": "Términos de Servicio",
  "and": "y",
  "privacy_policy": "Política de Privacidad",
  "create_account": "Crear cuenta",
  "already_have_account": "¿Ya tienes una cuenta?",
  "login_here": "Inicia sesión aquí",
  "discover_egypt": "Descubre Egipto",
  "book_amazing_activities": "Reserva actividades y experiencias increíbles",
  "scan_qr_code": "Escanear código QR",
  "search_activities": "Buscar actividades...",
  "popular_activities": "Actividades populares",
  "special_events": "Eventos especiales",
  "additional_services": "Servicios adicionales",
  "luxor_temple_tour": "Tour del Templo de Luxor",
  "hours": "horas",
  "per_person": "/persona",
  "book": "Reservar",
  "book_now": "Reservar ahora",
  "healthcare": "Atención médica",
  "medical_support": "Soporte médico 24/7",
  "spa_massage": "Spa y masajes",
  "relaxation_services": "Servicios de relajación",
  "request_service": "Solicitar servicio",
  "christmas_beach_party": "Fiesta navideña en la playa",
  "new_year_gala_dinner": "Cena de gala de Año Nuevo",
  "special_event": "Evento especial",
  "december": "Diciembre",
  "cultural": "Cultural",
  "language_english": "English",
  "language_arabic": "العربية",
  "language_german": "Deutsch",
  "language_spanish": "Español",
  "language_french": "Français",
  "language_italian": "Italiano",
  "language_russian": "Русский",
  "home": "Inicio",
  "excursions": "Excursiones",
  "events": "Eventos",
  "services": "Servicios",
  "favorites": "Favoritos",
  "search_placeholder": "Buscar excursiones, eventos...",
  "all": "Todo",
  "snorkeling": "Esnórquel",
  "diving": "Buceo",
  "safari": "Safari",
  "adventure": "Aventura",
  "view_all": "Ver todo",
  "trending_excursions": "Populares",
  "upcoming_events": "Próximos eventos",
  "quick_services": "Servicios rápidos",
  "connect": "Conectar",
  "available": "Disponible",
  "explore_excursions": "Explorar excursiones",
  "my_favorites": "Mis favoritos",
  "no_favorites_yet": "Sin favoritos aún",
  "start_adding_favorites": "¡Añade favoritos ahora!",
  "favorite_excursions": "Excursiones favoritas",
  "favorite_events": "Eventos favoritos",
  "connect_with_representative": "Contactar representante",
  "scan_qr_description": "Escanea el código QR para empezar",
  "close": "Cerrar",
  "select_date": "Fecha",
  "preferred_time": "Hora",
  "number_of_people": "Personas",
  "additional_notes": "Notas",
  "additional_notes_placeholder": "Solicitudes especiales...",
  "price_summary": "Precio",
  "service_fee": "Tarifa",
  "total": "Total",
  "cancel": "Cancelar",
  "confirm_booking": "Confirmar",
  "people": "personas",
  "person": "persona",
  "preferred_date": "Fecha preferida",
  "urgency_level": "Urgencia",
  "normal": "Normal",
  "urgent": "Urgente",
  "emergency": "Emergencia",
  "additional_details": "Detalles",
  "additional_details_placeholder": "Describa sus necesidades...",
  "service_request_info": "Le contactaremos en 30 minutos",
  "submit_request": "Enviar",
  "booking_confirmed": "¡Confirmado!",
  "service_requested": "¡Enviado!",
  "night_life": "Vida nocturna",
  "christmas": "Navidad",
  "new_year": "Año Nuevo",
  "select_time": "Hora",
  "excursion_red_sea_name": "Aventura de Snorkel en el Mar Rojo",
  "excursion_red_sea_desc": "Explora los hermosos arrecifes de coral y la colorida vida marina",
  "excursion_safari_name": "Experiencia de Safari en el Desierto",
  "excursion_safari_desc": "Emocionante aventura en el desierto con quads y paseos en camello",
  "excursion_scuba_name": "Buceo Profesional",
  "excursion_scuba_desc": "Experiencia de buceo en aguas profundas con instructores certificados",
  "excursion_luxor_name": "Tour del Templo de Luxor",
  "excursion_luxor_desc": "Visita templos y monumentos del antiguo Egipto",
  "excursion_bedouin_name": "Safari Nocturno Beduino",
  "excursion_bedouin_desc": "Vive la cultura beduina con cena y observación de estrellas",
  "excursion_parasailing_name": "Aventura de Parasailing",
  "excursion_parasailing_desc": "Vuela sobre el Mar Rojo con vistas impresionantes",
  "event_christmas_party_name": "Fiesta de Navidad en la Playa",
  "event_christmas_party_desc": "Celebra la Navidad en la playa con música y comida",
  "event_new_year_gala_name": "Noche de Gala de Año Nuevo",
  "event_new_year_gala_desc": "Recibe el año nuevo con una celebración espectacular",
  "event_night_club_name": "Experiencia en Club Nocturno",
  "event_night_club_desc": "Experiencia premium en club nocturno con DJs internacionales",
  "event_cultural_night_name": "Noche Cultural Egipcia",
  "event_cultural_night_desc": "Música, danza y cocina tradicional egipcia",
  "service_healthcare_name": "Atención Médica",
  "service_healthcare_desc": "Soporte médico 24/7",
  "service_spa_name": "Spa y Masaje",
  "service_spa_desc": "Servicios de relajación",
  "service_doctor_name": "Consulta Médica",
  "service_doctor_desc": "En línea y en persona",
  "service_transfer_name": "Traslado al Aeropuerto",
  "service_transfer_desc": "Transporte privado",
  "service_trainer_name": "Entrenador Personal",
  "service_trainer_desc": "Fitness y bienestar",
  "service_guide_name": "Guía Turístico",
  "service_guide_desc": "Tours privados",
  "upcoming_bookings": "Próximas reservas",
  "my_bookings": "Mis reservas",
  "days_until": "días hasta",
  "today": "Hoy",
  "tomorrow": "Mañana",
  "cancel_booking": "Cancelar",
  "no_upcoming_bookings": "No hay reservas próximas",
  "booking_cancelled": "Reserva cancelada con éxito",
  "confirm": "Confirmar",
  "offers": "Ofertas",
  "real_estate": "Bienes Raíces",
  "shaleeh": "Chalet",
  "studio": "Estudio",
  "department": "Departamento",
  "villa": "Villa",
  "select_city": "Seleccionar ciudad",
  "onboarding_title_1": "Explora el mundo",
  "onboarding_subtitle_1": "Descubra tesoros ocultos y destinos impresionantes adaptados a sus gustos.",
  "onboarding_title_2": "Estancias de lujo",
  "onboarding_subtitle_2": "Disfrute de una hospitalidad de clase mundial en hoteles seleccionados y estancias únicas.",
  "onboarding_title_3": "Viaje sin esfuerzo",
  "onboarding_subtitle_3": "Planifique y reserve todo su viaje con facilidad, desde vuelos hasta recorridos locales.",
  "get_started": "Empezar",
  "skip": "Saltar"
};
static const Map<String,dynamic> _ar = {
  "hello": "اهلا",
  "choose_image": "اختر الصوره",
  "take_photo": "التقط صورة",
  "choose_from_gallery": "من المعرض",
  "back_to_role_selection": "العودة لاختيار الدور",
  "login_as_customer": "تسجيل الدخول كعميل",
  "enter_credentials_to_continue": "أدخل بياناتك للمتابعة",
  "continue_with_google": "المتابعة مع جوجل",
  "continue_with_apple": "المتابعة مع آبل",
  "or_continue_with_email": "أو المتابعة بالبريد الإلكتروني",
  "email_address": "عنوان البريد الإلكتروني",
  "email_placeholder": "you@example.com",
  "email_required": "البريد الإلكتروني مطلوب",
  "email_invalid": "البريد الإلكتروني غير صالح",
  "phone_number_required": "رقم الهاتف مطلوب",
  "phone_number_invalid": "رقم الهاتف غير صالح",
  "search_country": "بحث عن دولة",
  "otp_title": "رمز التحقق",
  "otp_subtitle": "لقد أرسلنا رمز التحقق إلى هاتفك",
  "verify": "تحقق",
  "resend_code": "إعادة إرسال الرمز",
  "didnt_receive_code": "لم تستلم الرمز؟",
  "otp_invalid": "رمز تحقق غير صالح",
  "password": "كلمة المرور",
  "password_placeholder": "••••••••",
  "password_required": "كلمة المرور مطلوبة",
  "password_length_error": "يجب أن تكون كلمة المرور 6 أحرف على الأقل",
  "remember_me": "تذكرني",
  "forgot_password": "نسيت كلمة المرور؟",
  "login": "تسجيل الدخول",
  "dont_have_account": "ليس لديك حساب؟",
  "register_now": "سجل الآن",
  "register_as_customer": "التسجيل كعميل",
  "create_account_to_get_started": "أنشئ حسابك للبدء",
  "or_register_with_email": "أو سجل بالبريد الإلكتروني",
  "full_name": "الاسم الكامل",
  "full_name_placeholder": "أحمد محمد",
  "phone_number": "رقم الهاتف",
  "phone_placeholder": "+20 123 456 7890",
  "confirm_password": "تأكيد كلمة المرور",
  "confirm_password_placeholder": "••••••••",
  "i_agree_to_the": "أوافق على",
  "terms_of_service": "شروط الخدمة",
  "and": "و",
  "privacy_policy": "سياسة الخصوصية",
  "create_account": "إنشاء حساب",
  "already_have_account": "لديك حساب بالفعل؟",
  "login_here": "سجل الدخول هنا",
  "discover_egypt": "اكتشف مصر",
  "book_amazing_activities": "احجز أنشطة وتجارب مذهلة",
  "scan_qr_code": "مسح رمز الاستجابة السريعة",
  "search_activities": "البحث عن الأنشطة...",
  "popular_activities": "الأنشطة الشائعة",
  "special_events": "الأحداث الخاصة",
  "additional_services": "خدمات إضافية",
  "luxor_temple_tour": "جولة معبد الأقصر",
  "hours": "ساعات",
  "per_person": "/شخص",
  "book": "احجز",
  "book_now": "احجز الآن",
  "healthcare": "الرعاية الصحية",
  "medical_support": "دعم طبي على مدار الساعة",
  "spa_massage": "سبا ومساج",
  "relaxation_services": "خدمات الاسترخاء",
  "request_service": "طلب الخدمة",
  "christmas_beach_party": "حفلة شاطئ عيد الميلاد",
  "new_year_gala_dinner": "عشاء احتفالي رأس السنة",
  "special_event": "حدث خاص",
  "december": "ديسمبر",
  "cultural": "ثقافي",
  "home": "الرئيسية",
  "excursions": "الرحلات",
  "events": "الفعاليات",
  "services": "الخدمات",
  "favorites": "المفضلة",
  "search_placeholder": "البحث عن الرحلات أو الفعاليات أو الخدمات...",
  "all": "الكل",
  "snorkeling": "الغطس",
  "diving": "الغوص",
  "safari": "سفاري",
  "adventure": "مغامرة",
  "view_all": "عرض الكل",
  "trending_excursions": "الرحلات الرائجة",
  "upcoming_events": "الفعاليات القادمة",
  "quick_services": "خدمات سريعة",
  "connect": "اتصل",
  "available": "متاح",
  "explore_excursions": "استكشف الرحلات",
  "my_favorites": "مفضلاتي",
  "no_favorites_yet": "لا توجد مفضلات بعد",
  "start_adding_favorites": "ابدأ بإضافة الرحلات والفعاليات إلى مفضلاتك!",
  "favorite_excursions": "الرحلات المفضلة",
  "favorite_events": "الفعاليات المفضلة",
  "connect_with_representative": "اتصل بالممثل",
  "scan_qr_description": "امسح رمز الاستجابة السريعة الخاص بممثلك للبدء",
  "close": "إغلاق",
  "select_date": "اختر التاريخ",
  "preferred_time": "الوقت المفضل",
  "number_of_people": "عدد الأشخاص",
  "additional_notes": "ملاحظات إضافية",
  "additional_notes_placeholder": "أي طلبات أو متطلبات خاصة...",
  "price_summary": "ملخص السعر",
  "service_fee": "رسوم الخدمة",
  "total": "الإجمالي",
  "cancel": "إلغاء",
  "confirm_booking": "تأكيد الحجز",
  "people": "أشخاص",
  "person": "شخص",
  "preferred_date": "التاريخ المفضل",
  "urgency_level": "مستوى الأولوية",
  "normal": "عادي",
  "urgent": "عاجل",
  "emergency": "طارئ",
  "additional_details": "تفاصيل إضافية",
  "additional_details_placeholder": "يرجى وصف احتياجاتك أو أي متطلبات خاصة...",
  "service_request_info": "سيتواصل فريقنا معك خلال 30 دقيقة لتأكيد طلب الخدمة",
  "submit_request": "إرسال الطلب",
  "booking_confirmed": "تم تأكيد الحجز!",
  "service_requested": "تم إرسال طلب الخدمة!",
  "night_life": "الحياة الليلية",
  "christmas": "عيد الميلاد",
  "new_year": "رأس السنة",
  "select_time": "اختر الوقت",
  "excursion_red_sea_name": "مغامرة الغوص في البحر الأحمر",
  "excursion_red_sea_desc": "استكشف الشعاب المرجانية الجميلة والحياة البحرية الملونة",
  "excursion_safari_name": "تجربة سفاري الصحراء",
  "excursion_safari_desc": "مغامرة صحراوية مثيرة مع الدراجات الرباعية وركوب الجمال",
  "excursion_scuba_name": "غوص سكوبا احترافي",
  "excursion_scuba_desc": "تجربة غوص في أعماق البحار مع مدربين معتمدين",
  "excursion_luxor_name": "جولة معبد الأقصر",
  "excursion_luxor_desc": "زيارة المعابد والآثار المصرية القديمة",
  "excursion_bedouin_name": "سفاري ليلي بدوي",
  "excursion_bedouin_desc": "تجربة الثقافة البدوية مع العشاء وتأمل النجوم",
  "excursion_parasailing_name": "مغامرة الباراشوت",
  "excursion_parasailing_desc": "حلق فوق البحر الأحمر مع مناظر خلابة",
  "event_christmas_party_name": "حفلة شاطئ الكريسماس",
  "event_christmas_party_desc": "احتفل بالكريسماس على الشاطئ مع الموسيقى والطعام",
  "event_new_year_gala_name": "حفل رأس السنة",
  "event_new_year_gala_desc": "استقبل العام الجديد باحتفال رائع",
  "event_night_club_name": "تجربة النادي الليلي",
  "event_night_club_desc": "تجربة نادي ليلي مميز مع دي جي عالميين",
  "event_cultural_night_name": "ليلة ثقافية مصرية",
  "event_cultural_night_desc": "موسيقى ورقص ومأكولات مصرية تقليدية",
  "service_healthcare_name": "رعاية صحية",
  "service_healthcare_desc": "دعم طبي على مدار 24 ساعة",
  "service_spa_name": "سبا وتدليك",
  "service_spa_desc": "خدمات الاسترخاء",
  "service_doctor_name": "استشارة طبيب",
  "service_doctor_desc": "عبر الإنترنت وشخصياً",
  "service_transfer_name": "نقل المطار",
  "service_transfer_desc": "نقل خاص",
  "service_trainer_name": "مدرب شخصي",
  "service_trainer_desc": "لياقة بدنية وصحة",
  "service_guide_name": "مرشد سياحي",
  "service_guide_desc": "جولات خاصة",
  "upcoming_bookings": "الحجوزات القادمة",
  "my_bookings": "حجوزاتي",
  "days_until": "أيام حتى",
  "today": "اليوم",
  "tomorrow": "غداً",
  "cancel_booking": "إلغاء الحجز",
  "no_upcoming_bookings": "لا توجد حجوزات قادمة",
  "booking_cancelled": "تم إلغاء الحجز بنجاح",
  "confirm": "تأكيد",
  "offers": "العروض",
  "real_estate": "العقارات",
  "shaleeh": "شاليهات",
  "studio": "ستوديو",
  "department": "شقق",
  "villa": "فيلات",
  "select_city": "اختر المدينة",
  "onboarding_title_1": "استكشف العالم",
  "onboarding_subtitle_1": "اكتشف الجواهر الخفية والوجهات الخلابة المصممة خصيصاً لك.",
  "onboarding_title_2": "إقامات فاخرة",
  "onboarding_subtitle_2": "جرب الضيافة العالمية في فنادق مختارة وإقامات فريدة.",
  "onboarding_title_3": "سفر بدون مجهود",
  "onboarding_subtitle_3": "خطط واحجز رحلتك بالكامل بسهولة، من الرحلات الجوية إلى الجولات المحلية.",
  "get_started": "ابدأ الآن",
  "skip": "تخطي"
};
static const Map<String, Map<String,dynamic>> mapLocales = {"zh": _zh, "ja": _ja, "de": _de, "ru": _ru, "pl": _pl, "en": _en, "it": _it, "fr": _fr, "es": _es, "ar": _ar};
}
