// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

// ignore_for_file: prefer_single_quotes, avoid_renaming_method_parameters, constant_identifier_names

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

class CodegenLoader extends AssetLoader{
  const CodegenLoader();

  @override
  Future<Map<String, dynamic>?> load(String path, Locale locale) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static const Map<String,dynamic> _de = {
  "hello": "Hallo",
  "choose_image": "Bild auswählen",
  "take_photo": "Foto aufnehmen",
  "choose_from_gallery": "Aus der Galerie wählen",
  "back_to_role_selection": "Zurück zur Rollenauswahl",
  "login_as_customer": "Als Kunde anmelden",
  "enter_credentials_to_continue": "Geben Sie Ihre Anmeldedaten ein, um fortzufahren",
  "continue_with_google": "Mit Google fortfahren",
  "continue_with_apple": "Mit Apple fortfahren",
  "or_continue_with_email": "Oder mit E-Mail fortfahren",
  "email_address": "E-Mail-Adresse",
  "email_placeholder": "you@example.com",
  "password": "Passwort",
  "password_placeholder": "••••••••",
  "remember_me": "Angemeldet bleiben",
  "forgot_password": "Passwort vergessen?",
  "login": "Anmelden",
  "dont_have_account": "Haben Sie noch kein Konto?",
  "register_now": "Jetzt registrieren",
  "register_as_customer": "Als Kunde registrieren",
  "create_account_to_get_started": "Erstellen Sie Ihr Konto, um zu beginnen",
  "or_register_with_email": "Oder mit E-Mail registrieren",
  "full_name": "Vollständiger Name",
  "full_name_placeholder": "Max Mustermann",
  "phone_number": "Telefonnummer",
  "phone_placeholder": "+49 123 456 7890",
  "confirm_password": "Passwort bestätigen",
  "confirm_password_placeholder": "••••••••",
  "i_agree_to_the": "Ich stimme den",
  "terms_of_service": "Nutzungsbedingungen",
  "and": "und",
  "privacy_policy": "Datenschutzrichtlinie",
  "create_account": "Konto erstellen",
  "already_have_account": "Haben Sie bereits ein Konto?",
  "login_here": "Hier anmelden",
  "discover_egypt": "Ägypten entdecken",
  "book_amazing_activities": "Buchen Sie erstaunliche Aktivitäten und Erlebnisse",
  "scan_qr_code": "QR-Code scannen",
  "search_activities": "Aktivitäten suchen...",
  "popular_activities": "Beliebte Aktivitäten",
  "special_events": "Besondere Veranstaltungen",
  "additional_services": "Zusätzliche Dienstleistungen",
  "luxor_temple_tour": "Luxor Tempel Tour",
  "hours": "Stunden",
  "per_person": "/Person",
  "book": "Buchen",
  "book_now": "Jetzt buchen",
  "healthcare": "Gesundheitswesen",
  "medical_support": "24/7 Medizinische Unterstützung",
  "spa_massage": "Spa & Massage",
  "relaxation_services": "Entspannungsdienstleistungen",
  "request_service": "Service anfordern",
  "christmas_beach_party": "Weihnachts-Strandparty",
  "new_year_gala_dinner": "Neujahrs-Gala-Dinner",
  "special_event": "Besonderes Ereignis",
  "december": "Dezember",
  "cultural": "Kulturell",
  "language_english": "English",
  "language_arabic": "العربية",
  "language_german": "Deutsch",
  "language_spanish": "Español",
  "language_french": "Français",
  "language_italian": "Italiano",
  "language_russian": "Русский",
  "home": "Start",
  "excursions": "Ausflüge",
  "events": "Events",
  "services": "Dienste",
  "favorites": "Favoriten",
  "search_placeholder": "Ausflüge, Events suchen...",
  "all": "Alle",
  "snorkeling": "Schnorcheln",
  "diving": "Tauchen",
  "safari": "Safari",
  "adventure": "Abenteuer",
  "view_all": "Alle anzeigen",
  "trending_excursions": "Beliebte Ausflüge",
  "upcoming_events": "Kommende Events",
  "quick_services": "Schnelldienste",
  "connect": "Kontakt",
  "available": "Verfügbar",
  "explore_excursions": "Ausflüge entdecken",
  "my_favorites": "Meine Favoriten",
  "no_favorites_yet": "Noch keine Favoriten",
  "start_adding_favorites": "Fügen Sie Favoriten hinzu!",
  "favorite_excursions": "Lieblingsausflüge",
  "favorite_events": "Lieblingsevents",
  "connect_with_representative": "Vertreter kontaktieren",
  "scan_qr_description": "QR-Code scannen zum Starten",
  "close": "Schließen",
  "select_date": "Datum",
  "preferred_time": "Zeit",
  "number_of_people": "Personen",
  "additional_notes": "Notizen",
  "additional_notes_placeholder": "Sonderwünsche...",
  "price_summary": "Preis",
  "service_fee": "Gebühr",
  "total": "Gesamt",
  "cancel": "Abbrechen",
  "confirm_booking": "Bestätigen",
  "people": "Personen",
  "person": "Person",
  "preferred_date": "Wunschdatum",
  "urgency_level": "Dringlichkeit",
  "normal": "Normal",
  "urgent": "Dringend",
  "emergency": "Notfall",
  "additional_details": "Details",
  "additional_details_placeholder": "Beschreiben Sie Ihre Bedürfnisse...",
  "service_request_info": "Wir melden uns in 30 Min.",
  "submit_request": "Senden",
  "booking_confirmed": "Bestätigt!",
  "service_requested": "Gesendet!",
  "night_life": "Nachtleben",
  "christmas": "Weihnachten",
  "new_year": "Neujahr",
  "select_time": "Zeit",
  "excursion_red_sea_name": "Rotes Meer Schnorchel-Abenteuer",
  "excursion_red_sea_desc": "Entdecken Sie die wunderschönen Korallenriffe und das bunte Meeresleben",
  "excursion_safari_name": "Wüsten-Safari Erlebnis",
  "excursion_safari_desc": "Aufregendes Wüstenabenteuer mit Quads und Kamelreiten",
  "excursion_scuba_name": "Professionelles Tauchen",
  "excursion_scuba_desc": "Tiefseetaucherlebnis mit zertifizierten Tauchlehrern",
  "excursion_luxor_name": "Luxor Tempel Tour",
  "excursion_luxor_desc": "Besuchen Sie alte ägyptische Tempel und Denkmäler",
  "excursion_bedouin_name": "Beduinen Nacht-Safari",
  "excursion_bedouin_desc": "Erleben Sie die Beduinenkultur mit Abendessen und Sternenbeobachtung",
  "excursion_parasailing_name": "Parasailing Abenteuer",
  "excursion_parasailing_desc": "Schweben Sie über dem Roten Meer mit atemberaubender Aussicht",
  "event_christmas_party_name": "Weihnachts-Strandparty",
  "event_christmas_party_desc": "Feiern Sie Weihnachten am Strand mit Musik und Essen",
  "event_new_year_gala_name": "Neujahrs-Gala-Nacht",
  "event_new_year_gala_desc": "Begrüßen Sie das neue Jahr mit einer spektakulären Feier",
  "event_night_club_name": "Nachtclub-Erlebnis",
  "event_night_club_desc": "Premium-Nachtclub-Erlebnis mit internationalen DJs",
  "event_cultural_night_name": "Ägyptische Kulturnacht",
  "event_cultural_night_desc": "Traditionelle ägyptische Musik, Tanz und Küche",
  "service_healthcare_name": "Gesundheitswesen",
  "service_healthcare_desc": "24/7 Medizinische Unterstützung",
  "service_spa_name": "Spa & Massage",
  "service_spa_desc": "Entspannungsdienste",
  "service_doctor_name": "Arztkonsultation",
  "service_doctor_desc": "Online & Persönlich",
  "service_transfer_name": "Flughafentransfer",
  "service_transfer_desc": "Privater Transport",
  "service_trainer_name": "Personal Trainer",
  "service_trainer_desc": "Fitness & Wellness",
  "service_guide_name": "Reiseleiter",
  "service_guide_desc": "Private Touren"
};
static const Map<String,dynamic> _ru = {
  "hello": "Привет",
  "choose_image": "Выбрать изображение",
  "take_photo": "Сделать фото",
  "choose_from_gallery": "Выбрать из галереи",
  "back_to_role_selection": "Вернуться к выбору роли",
  "login_as_customer": "Войти как клиент",
  "enter_credentials_to_continue": "Введите свои данные для продолжения",
  "continue_with_google": "Продолжить с Google",
  "continue_with_apple": "Продолжить с Apple",
  "or_continue_with_email": "Или продолжить с электронной почтой",
  "email_address": "Адрес электронной почты",
  "email_placeholder": "you@example.com",
  "password": "Пароль",
  "password_placeholder": "••••••••",
  "remember_me": "Запомнить меня",
  "forgot_password": "Забыли пароль?",
  "login": "Войти",
  "dont_have_account": "Нет аккаунта?",
  "register_now": "Зарегистрироваться сейчас",
  "register_as_customer": "Зарегистрироваться как клиент",
  "create_account_to_get_started": "Создайте свой аккаунт, чтобы начать",
  "or_register_with_email": "Или зарегистрироваться с электронной почтой",
  "full_name": "Полное имя",
  "full_name_placeholder": "Иван Иванов",
  "phone_number": "Номер телефона",
  "phone_placeholder": "+7 123 456 7890",
  "confirm_password": "Подтвердить пароль",
  "confirm_password_placeholder": "••••••••",
  "i_agree_to_the": "Я согласен с",
  "terms_of_service": "Условиями обслуживания",
  "and": "и",
  "privacy_policy": "Политикой конфиденциальности",
  "create_account": "Создать аккаунт",
  "already_have_account": "Уже есть аккаунт?",
  "login_here": "Войти здесь",
  "discover_egypt": "Откройте Египет",
  "book_amazing_activities": "Забронируйте удивительные мероприятия и впечатления",
  "scan_qr_code": "Сканировать QR-код",
  "search_activities": "Поиск мероприятий...",
  "popular_activities": "Популярные мероприятия",
  "special_events": "Специальные события",
  "additional_services": "Дополнительные услуги",
  "luxor_temple_tour": "Экскурсия по храму Луксора",
  "hours": "часов",
  "per_person": "/человек",
  "book": "Забронировать",
  "book_now": "Забронировать сейчас",
  "healthcare": "Здравоохранение",
  "medical_support": "Медицинская поддержка 24/7",
  "spa_massage": "Спа и массаж",
  "relaxation_services": "Услуги релаксации",
  "request_service": "Запросить услугу",
  "christmas_beach_party": "Рождественская пляжная вечеринка",
  "new_year_gala_dinner": "Новогодний гала-ужин",
  "special_event": "Специальное событие",
  "december": "Декабрь",
  "cultural": "Культурный",
  "language_english": "English",
  "language_arabic": "العربية",
  "language_german": "Deutsch",
  "language_spanish": "Español",
  "language_french": "Français",
  "language_italian": "Italiano",
  "language_russian": "Русский",
  "home": "Главная",
  "excursions": "Экскурсии",
  "events": "События",
  "services": "Услуги",
  "favorites": "Избранное",
  "search_placeholder": "Поиск экскурсий, событий...",
  "all": "Все",
  "snorkeling": "Снорклинг",
  "diving": "Дайвинг",
  "safari": "Сафари",
  "adventure": "Приключения",
  "view_all": "Все",
  "trending_excursions": "Популярные",
  "upcoming_events": "Предстоящие",
  "quick_services": "Быстрые услуги",
  "connect": "Связаться",
  "available": "Доступно",
  "explore_excursions": "Обзор экскурсий",
  "my_favorites": "Мое избранное",
  "no_favorites_yet": "Нет избранного",
  "start_adding_favorites": "Добавьте в избранное!",
  "favorite_excursions": "Любимые экскурсии",
  "favorite_events": "Любимые события",
  "connect_with_representative": "Связаться с представителем",
  "scan_qr_description": "Сканируйте QR для начала",
  "close": "Закрыть",
  "select_date": "Дата",
  "preferred_time": "Время",
  "number_of_people": "Человек",
  "additional_notes": "Заметки",
  "additional_notes_placeholder": "Особые пожелания...",
  "price_summary": "Цена",
  "service_fee": "Сбор",
  "total": "Итого",
  "cancel": "Отмена",
  "confirm_booking": "Подтвердить",
  "people": "чел.",
  "person": "чел.",
  "preferred_date": "Желаемая дата",
  "urgency_level": "Срочность",
  "normal": "Обычно",
  "urgent": "Срочно",
  "emergency": "Экстренно",
  "additional_details": "Детали",
  "additional_details_placeholder": "Опишите ваши потребности...",
  "service_request_info": "Свяжемся через 30 мин",
  "submit_request": "Отправить",
  "booking_confirmed": "Подтверждено!",
  "service_requested": "Отправлено!",
  "night_life": "Ночная жизнь",
  "christmas": "Рождество",
  "new_year": "Новый год",
  "select_time": "Время",
  "excursion_red_sea_name": "Снорклинг в Красном море",
  "excursion_red_sea_desc": "Исследуйте красивые коралловые рифы и красочную морскую жизнь",
  "excursion_safari_name": "Сафари в пустыне",
  "excursion_safari_desc": "Захватывающее приключение в пустыне на квадроциклах и верблюдах",
  "excursion_scuba_name": "Профессиональный дайвинг",
  "excursion_scuba_desc": "Глубоководное погружение с сертифицированными инструкторами",
  "excursion_luxor_name": "Тур в Луксорский храм",
  "excursion_luxor_desc": "Посетите древние египетские храмы и памятники",
  "excursion_bedouin_name": "Ночное сафари бедуинов",
  "excursion_bedouin_desc": "Познакомьтесь с культурой бедуинов за ужином и наблюдением за звездами",
  "excursion_parasailing_name": "Парасейлинг",
  "excursion_parasailing_desc": "Парите над Красным морем с захватывающими видами",
  "event_christmas_party_name": "Рождественская пляжная вечеринка",
  "event_christmas_party_desc": "Отпразднуйте Рождество на пляже с музыкой и едой",
  "event_new_year_gala_name": "Новогодний гала-вечер",
  "event_new_year_gala_desc": "Встречайте Новый год грандиозным праздником",
  "event_night_club_name": "Ночной клуб",
  "event_night_club_desc": "Премиальный ночной клуб с международными диджеями",
  "event_cultural_night_name": "Египетская культурная ночь",
  "event_cultural_night_desc": "Традиционная египетская музыка, танцы и кухня",
  "service_healthcare_name": "Здравоохранение",
  "service_healthcare_desc": "Круглосуточная медицинская поддержка",
  "service_spa_name": "Спа и массаж",
  "service_spa_desc": "Услуги релаксации",
  "service_doctor_name": "Консультация врача",
  "service_doctor_desc": "Онлайн и лично",
  "service_transfer_name": "Трансфер из аэропорта",
  "service_transfer_desc": "Частный транспорт",
  "service_trainer_name": "Персональный тренер",
  "service_trainer_desc": "Фитнес и здоровье",
  "service_guide_name": "Туристический гид",
  "service_guide_desc": "Частные туры"
};
static const Map<String,dynamic> _en = {
  "hello": "Hello",
  "choose_image": "Choose Image",
  "take_photo": "Take Photo",
  "choose_from_gallery": "Choose from Gallery",
  "back_to_role_selection": "Back to role selection",
  "login_as_customer": "Login as Customer",
  "enter_credentials_to_continue": "Enter your credentials to continue",
  "continue_with_google": "Continue with Google",
  "continue_with_apple": "Continue with Apple",
  "or_continue_with_email": "Or continue with email",
  "email_address": "Email Address",
  "email_placeholder": "you@example.com",
  "password": "Password",
  "password_placeholder": "••••••••",
  "remember_me": "Remember me",
  "forgot_password": "Forgot password?",
  "login": "Login",
  "dont_have_account": "Don't have an account?",
  "register_now": "Register Now",
  "language_english": "English",
  "language_arabic": "العربية",
  "language_german": "Deutsch",
  "language_spanish": "Español",
  "language_french": "Français",
  "language_italian": "Italiano",
  "language_russian": "Русский",
  "register_as_customer": "Register as Customer",
  "create_account_to_get_started": "Create your account to get started",
  "or_register_with_email": "Or register with email",
  "full_name": "Full Name",
  "full_name_placeholder": "John Doe",
  "phone_number": "Phone Number",
  "phone_placeholder": "+20 123 456 7890",
  "confirm_password": "Confirm Password",
  "confirm_password_placeholder": "••••••••",
  "i_agree_to_the": "I agree to the",
  "terms_of_service": "Terms of Service",
  "and": "and",
  "privacy_policy": "Privacy Policy",
  "create_account": "Create Account",
  "already_have_account": "Already have an account?",
  "login_here": "Login Here",
  "discover_egypt": "Discover Egypt",
  "book_amazing_activities": "Book amazing activities and experiences",
  "scan_qr_code": "Scan QR Code",
  "search_activities": "Search activities...",
  "popular_activities": "Popular Activities",
  "special_events": "Special Events",
  "additional_services": "Additional Services",
  "luxor_temple_tour": "Luxor Temple Tour",
  "hours": "hours",
  "per_person": "/person",
  "book": "Book",
  "book_now": "Book Now",
  "healthcare": "Healthcare",
  "medical_support": "24/7 Medical Support",
  "spa_massage": "Spa & Massage",
  "relaxation_services": "Relaxation Services",
  "request_service": "Request Service",
  "christmas_beach_party": "Christmas Beach Party",
  "new_year_gala_dinner": "New Year Gala Dinner",
  "special_event": "Special Event",
  "december": "December",
  "cultural": "Cultural",
  "home": "Home",
  "excursions": "Excursions",
  "events": "Events",
  "services": "Services",
  "favorites": "Favorites",
  "search_placeholder": "Search excursions, events, or services...",
  "all": "All",
  "snorkeling": "Snorkeling",
  "diving": "Diving",
  "safari": "Safari",
  "adventure": "Adventure",
  "view_all": "View All",
  "trending_excursions": "Trending Excursions",
  "upcoming_events": "Upcoming Events",
  "quick_services": "Quick Services",
  "connect": "Connect",
  "available": "Available",
  "explore_excursions": "Explore Excursions",
  "my_favorites": "My Favorites",
  "no_favorites_yet": "No favorites yet",
  "start_adding_favorites": "Start adding excursions and events to your favorites!",
  "favorite_excursions": "Favorite Excursions",
  "favorite_events": "Favorite Events",
  "connect_with_representative": "Connect with Representative",
  "scan_qr_description": "Scan your representative's QR code to get started",
  "close": "Close",
  "select_date": "Select Date",
  "preferred_time": "Preferred Time",
  "number_of_people": "Number of People",
  "additional_notes": "Additional Notes",
  "additional_notes_placeholder": "Any special requests or requirements...",
  "price_summary": "Price Summary",
  "service_fee": "Service Fee",
  "total": "Total",
  "cancel": "Cancel",
  "confirm_booking": "Confirm Booking",
  "people": "people",
  "person": "person",
  "preferred_date": "Preferred Date",
  "urgency_level": "Urgency Level",
  "normal": "Normal",
  "urgent": "Urgent",
  "emergency": "Emergency",
  "additional_details": "Additional Details",
  "additional_details_placeholder": "Please describe your needs or any specific requirements...",
  "service_request_info": "Our team will contact you within 30 minutes to confirm your service request",
  "submit_request": "Submit Request",
  "booking_confirmed": "Booking Confirmed!",
  "service_requested": "Service Request Submitted!",
  "night_life": "Night Life",
  "christmas": "Christmas",
  "new_year": "New Year",
  "select_time": "Select time",
  "excursion_red_sea_name": "Red Sea Snorkeling Adventure",
  "excursion_red_sea_desc": "Explore the beautiful coral reefs and colorful marine life",
  "excursion_safari_name": "Desert Safari Experience",
  "excursion_safari_desc": "Thrilling desert adventure with quad bikes and camel rides",
  "excursion_scuba_name": "Professional Scuba Diving",
  "excursion_scuba_desc": "Deep sea diving experience with certified instructors",
  "excursion_luxor_name": "Luxor Temple Tour",
  "excursion_luxor_desc": "Visit ancient Egyptian temples and monuments",
  "excursion_bedouin_name": "Bedouin Night Safari",
  "excursion_bedouin_desc": "Experience Bedouin culture with dinner and stargazing",
  "excursion_parasailing_name": "Parasailing Adventure",
  "excursion_parasailing_desc": "Soar above the Red Sea with breathtaking views",
  "event_christmas_party_name": "Christmas Beach Party",
  "event_christmas_party_desc": "Celebrate Christmas on the beach with music and food",
  "event_new_year_gala_name": "New Year Gala Night",
  "event_new_year_gala_desc": "Ring in the new year with a spectacular celebration",
  "event_night_club_name": "Night Club Experience",
  "event_night_club_desc": "Premium nightclub experience with international DJs",
  "event_cultural_night_name": "Egyptian Cultural Night",
  "event_cultural_night_desc": "Traditional Egyptian music, dance, and cuisine",
  "service_healthcare_name": "Healthcare",
  "service_healthcare_desc": "24/7 Medical Support",
  "service_spa_name": "Spa & Massage",
  "service_spa_desc": "Relaxation Services",
  "service_doctor_name": "Doctor Consultation",
  "service_doctor_desc": "Online & In-person",
  "service_transfer_name": "Airport Transfer",
  "service_transfer_desc": "Private Transportation",
  "service_trainer_name": "Personal Trainer",
  "service_trainer_desc": "Fitness & Wellness",
  "service_guide_name": "Tour Guide",
  "service_guide_desc": "Private Tours"
};
static const Map<String,dynamic> _it = {
  "hello": "Ciao",
  "choose_image": "Scegli immagine",
  "take_photo": "Scatta foto",
  "choose_from_gallery": "Scegli dalla galleria",
  "back_to_role_selection": "Torna alla selezione del ruolo",
  "login_as_customer": "Accedi come cliente",
  "enter_credentials_to_continue": "Inserisci le tue credenziali per continuare",
  "continue_with_google": "Continua con Google",
  "continue_with_apple": "Continua con Apple",
  "or_continue_with_email": "O continua con l'email",
  "email_address": "Indirizzo email",
  "email_placeholder": "you@example.com",
  "password": "Password",
  "password_placeholder": "••••••••",
  "remember_me": "Ricordami",
  "forgot_password": "Password dimenticata?",
  "login": "Accedi",
  "dont_have_account": "Non hai un account?",
  "register_now": "Registrati ora",
  "register_as_customer": "Registrati come cliente",
  "create_account_to_get_started": "Crea il tuo account per iniziare",
  "or_register_with_email": "O registrati con l'email",
  "full_name": "Nome completo",
  "full_name_placeholder": "Mario Rossi",
  "phone_number": "Numero di telefono",
  "phone_placeholder": "+39 123 456 7890",
  "confirm_password": "Conferma password",
  "confirm_password_placeholder": "••••••••",
  "i_agree_to_the": "Accetto i",
  "terms_of_service": "Termini di Servizio",
  "and": "e",
  "privacy_policy": "Informativa sulla Privacy",
  "create_account": "Crea account",
  "already_have_account": "Hai già un account?",
  "login_here": "Accedi qui",
  "discover_egypt": "Scopri l'Egitto",
  "book_amazing_activities": "Prenota attività ed esperienze incredibili",
  "scan_qr_code": "Scansiona codice QR",
  "search_activities": "Cerca attività...",
  "popular_activities": "Attività popolari",
  "special_events": "Eventi speciali",
  "additional_services": "Servizi aggiuntivi",
  "luxor_temple_tour": "Tour del Tempio di Luxor",
  "hours": "ore",
  "per_person": "/persona",
  "book": "Prenota",
  "book_now": "Prenota ora",
  "healthcare": "Assistenza sanitaria",
  "medical_support": "Supporto medico 24/7",
  "spa_massage": "Spa e massaggi",
  "relaxation_services": "Servizi di rilassamento",
  "request_service": "Richiedi servizio",
  "christmas_beach_party": "Festa di Natale in spiaggia",
  "new_year_gala_dinner": "Cena di gala di Capodanno",
  "special_event": "Evento speciale",
  "december": "Dicembre",
  "cultural": "Culturale",
  "language_english": "English",
  "language_arabic": "العربية",
  "language_german": "Deutsch",
  "language_spanish": "Español",
  "language_french": "Français",
  "language_italian": "Italiano",
  "language_russian": "Русский",
  "home": "Home",
  "excursions": "Escursioni",
  "events": "Eventi",
  "services": "Servizi",
  "favorites": "Preferiti",
  "search_placeholder": "Cerca escursioni, eventi...",
  "all": "Tutti",
  "snorkeling": "Snorkeling",
  "diving": "Immersioni",
  "safari": "Safari",
  "adventure": "Avventura",
  "view_all": "Vedi tutto",
  "trending_excursions": "Di tendenza",
  "upcoming_events": "Prossimi eventi",
  "quick_services": "Servizi rapidi",
  "connect": "Connetti",
  "available": "Disponibile",
  "explore_excursions": "Esplora escursioni",
  "my_favorites": "I miei preferiti",
  "no_favorites_yet": "Nessun preferito",
  "start_adding_favorites": "Aggiungi ai preferiti!",
  "favorite_excursions": "Escursioni preferite",
  "favorite_events": "Eventi preferiti",
  "connect_with_representative": "Contatta rappresentante",
  "scan_qr_description": "Scansiona QR per iniziare",
  "close": "Chiudi",
  "select_date": "Data",
  "preferred_time": "Ora",
  "number_of_people": "Persone",
  "additional_notes": "Note",
  "additional_notes_placeholder": "Richieste speciali...",
  "price_summary": "Prezzo",
  "service_fee": "Commissione",
  "total": "Totale",
  "cancel": "Annulla",
  "confirm_booking": "Conferma",
  "people": "persone",
  "person": "persona",
  "preferred_date": "Data preferita",
  "urgency_level": "Urgenza",
  "normal": "Normale",
  "urgent": "Urgente",
  "emergency": "Emergenza",
  "additional_details": "Dettagli",
  "additional_details_placeholder": "Descrivi le tue esigenze...",
  "service_request_info": "Ti contatteremo in 30 min",
  "submit_request": "Invia",
  "booking_confirmed": "Confermato!",
  "service_requested": "Inviato!",
  "night_life": "Vita notturna",
  "christmas": "Natale",
  "new_year": "Capodanno",
  "select_time": "Ora",
  "excursion_red_sea_name": "Avventura di Snorkeling nel Mar Rosso",
  "excursion_red_sea_desc": "Esplora le bellissime barriere coralline e la colorata vita marina",
  "excursion_safari_name": "Esperienza Safari nel Deserto",
  "excursion_safari_desc": "Emozionante avventura nel deserto con quad e giri in cammello",
  "excursion_scuba_name": "Immersioni Subacquee Professionali",
  "excursion_scuba_desc": "Esperienza di immersione in acque profonde con istruttori certificati",
  "excursion_luxor_name": "Tour del Tempio di Luxor",
  "excursion_luxor_desc": "Visita antichi templi e monumenti egizi",
  "excursion_bedouin_name": "Safari Notturno Beduino",
  "excursion_bedouin_desc": "Vivi la cultura beduina con cena e osservazione delle stelle",
  "excursion_parasailing_name": "Avventura di Parasailing",
  "excursion_parasailing_desc": "Vola sopra il Mar Rosso con viste mozzafiato",
  "event_christmas_party_name": "Festa di Natale in Spiaggia",
  "event_christmas_party_desc": "Festeggia il Natale in spiaggia con musica e cibo",
  "event_new_year_gala_name": "Serata di Gala di Capodanno",
  "event_new_year_gala_desc": "Accogli il nuovo anno con una celebrazione spettacolare",
  "event_night_club_name": "Esperienza Night Club",
  "event_night_club_desc": "Esperienza premium in discoteca con DJ internazionali",
  "event_cultural_night_name": "Notte Culturale Egiziana",
  "event_cultural_night_desc": "Musica, danza e cucina tradizionale egiziana",
  "service_healthcare_name": "Assistenza Sanitaria",
  "service_healthcare_desc": "Supporto medico 24/7",
  "service_spa_name": "Spa e Massaggi",
  "service_spa_desc": "Servizi di relax",
  "service_doctor_name": "Consulto Medico",
  "service_doctor_desc": "Online e di persona",
  "service_transfer_name": "Trasferimento Aeroportuale",
  "service_transfer_desc": "Trasporto privato",
  "service_trainer_name": "Personal Trainer",
  "service_trainer_desc": "Fitness e benessere",
  "service_guide_name": "Guida Turistica",
  "service_guide_desc": "Tour privati"
};
static const Map<String,dynamic> _fr = {
  "hello": "Bonjour",
  "choose_image": "Choisir une image",
  "take_photo": "Prendre une photo",
  "choose_from_gallery": "Choisir dans la galerie",
  "back_to_role_selection": "Retour à la sélection de rôle",
  "login_as_customer": "Se connecter en tant que client",
  "enter_credentials_to_continue": "Entrez vos identifiants pour continuer",
  "continue_with_google": "Continuer avec Google",
  "continue_with_apple": "Continuer avec Apple",
  "or_continue_with_email": "Ou continuer avec l'e-mail",
  "email_address": "Adresse e-mail",
  "email_placeholder": "you@example.com",
  "password": "Mot de passe",
  "password_placeholder": "••••••••",
  "remember_me": "Se souvenir de moi",
  "forgot_password": "Mot de passe oublié ?",
  "login": "Se connecter",
  "dont_have_account": "Vous n'avez pas de compte ?",
  "register_now": "S'inscrire maintenant",
  "register_as_customer": "S'inscrire en tant que client",
  "create_account_to_get_started": "Créez votre compte pour commencer",
  "or_register_with_email": "Ou s'inscrire avec l'e-mail",
  "full_name": "Nom complet",
  "full_name_placeholder": "Jean Dupont",
  "phone_number": "Numéro de téléphone",
  "phone_placeholder": "+33 1 23 45 67 89",
  "confirm_password": "Confirmer le mot de passe",
  "confirm_password_placeholder": "••••••••",
  "i_agree_to_the": "J'accepte les",
  "terms_of_service": "Conditions de Service",
  "and": "et",
  "privacy_policy": "Politique de Confidentialité",
  "create_account": "Créer un compte",
  "already_have_account": "Vous avez déjà un compte ?",
  "login_here": "Connectez-vous ici",
  "discover_egypt": "Découvrir l'Égypte",
  "book_amazing_activities": "Réservez des activités et expériences incroyables",
  "scan_qr_code": "Scanner le code QR",
  "search_activities": "Rechercher des activités...",
  "popular_activities": "Activités populaires",
  "special_events": "Événements spéciaux",
  "additional_services": "Services supplémentaires",
  "luxor_temple_tour": "Visite du temple de Louxor",
  "hours": "heures",
  "per_person": "/personne",
  "book": "Réserver",
  "book_now": "Réserver maintenant",
  "healthcare": "Soins de santé",
  "medical_support": "Support médical 24/7",
  "spa_massage": "Spa et massage",
  "relaxation_services": "Services de relaxation",
  "request_service": "Demander un service",
  "christmas_beach_party": "Fête de Noël sur la plage",
  "new_year_gala_dinner": "Dîner de gala du Nouvel An",
  "special_event": "Événement spécial",
  "december": "Décembre",
  "cultural": "Culturel",
  "language_english": "English",
  "language_arabic": "العربية",
  "language_german": "Deutsch",
  "language_spanish": "Español",
  "language_french": "Français",
  "language_italian": "Italiano",
  "language_russian": "Русский",
  "home": "Accueil",
  "excursions": "Excursions",
  "events": "Événements",
  "services": "Services",
  "favorites": "Favoris",
  "search_placeholder": "Rechercher excursions, événements...",
  "all": "Tout",
  "snorkeling": "Plongée",
  "diving": "Plongée sous-marine",
  "safari": "Safari",
  "adventure": "Aventure",
  "view_all": "Voir tout",
  "trending_excursions": "Excursions populaires",
  "upcoming_events": "Événements à venir",
  "quick_services": "Services rapides",
  "connect": "Connecter",
  "available": "Disponible",
  "explore_excursions": "Explorer les excursions",
  "my_favorites": "Mes favoris",
  "no_favorites_yet": "Pas encore de favoris",
  "start_adding_favorites": "Commencez à ajouter des favoris !",
  "favorite_excursions": "Excursions favorites",
  "favorite_events": "Événements favoris",
  "connect_with_representative": "Contacter un représentant",
  "scan_qr_description": "Scannez le code QR pour commencer",
  "close": "Fermer",
  "select_date": "Date",
  "preferred_time": "Heure",
  "number_of_people": "Personnes",
  "additional_notes": "Notes",
  "additional_notes_placeholder": "Demandes spéciales...",
  "price_summary": "Prix",
  "service_fee": "Frais",
  "total": "Total",
  "cancel": "Annuler",
  "confirm_booking": "Confirmer",
  "people": "personnes",
  "person": "personne",
  "preferred_date": "Date préférée",
  "urgency_level": "Urgence",
  "normal": "Normal",
  "urgent": "Urgent",
  "emergency": "Urgence",
  "additional_details": "Détails",
  "additional_details_placeholder": "Décrivez vos besoins...",
  "service_request_info": "Nous vous contacterons dans 30 min",
  "submit_request": "Envoyer",
  "booking_confirmed": "Confirmé !",
  "service_requested": "Envoyé !",
  "night_life": "Vie nocturne",
  "christmas": "Noël",
  "new_year": "Nouvel An",
  "select_time": "Heure",
  "excursion_red_sea_name": "Aventure de plongée en apnée en Mer Rouge",
  "excursion_red_sea_desc": "Explorez les magnifiques récifs coralliens et la vie marine colorée",
  "excursion_safari_name": "Expérience Safari dans le Désert",
  "excursion_safari_desc": "Aventure palpitante dans le désert avec quad et balade à dos de chameau",
  "excursion_scuba_name": "Plongée sous-marine professionnelle",
  "excursion_scuba_desc": "Expérience de plongée en haute mer avec des instructeurs certifiés",
  "excursion_luxor_name": "Visite du temple de Louxor",
  "excursion_luxor_desc": "Visitez les temples et monuments de l'Égypte ancienne",
  "excursion_bedouin_name": "Safari nocturne bédouin",
  "excursion_bedouin_desc": "Vivez la culture bédouine avec dîner et observation des étoiles",
  "excursion_parasailing_name": "Aventure en parachute ascensionnel",
  "excursion_parasailing_desc": "Volez au-dessus de la Mer Rouge avec des vues à couper le souffle",
  "event_christmas_party_name": "Fête de Noël sur la plage",
  "event_christmas_party_desc": "Célébrez Noël sur la plage avec musique et nourriture",
  "event_new_year_gala_name": "Soirée de Gala du Nouvel An",
  "event_new_year_gala_desc": "Fêtez la nouvelle année avec une célébration spectaculaire",
  "event_night_club_name": "Expérience Night Club",
  "event_night_club_desc": "Expérience de boîte de nuit premium avec des DJ internationaux",
  "event_cultural_night_name": "Soirée culturelle égyptienne",
  "event_cultural_night_desc": "Musique traditionnelle égyptienne, danse et cuisine",
  "service_healthcare_name": "Soins de santé",
  "service_healthcare_desc": "Assistance médicale 24/7",
  "service_spa_name": "Spa & Massage",
  "service_spa_desc": "Services de relaxation",
  "service_doctor_name": "Consultation médicale",
  "service_doctor_desc": "En ligne et en personne",
  "service_transfer_name": "Transfert aéroport",
  "service_transfer_desc": "Transport privé",
  "service_trainer_name": "Entraîneur personnel",
  "service_trainer_desc": "Fitness et bien-être",
  "service_guide_name": "Guide touristique",
  "service_guide_desc": "Visites privées"
};
static const Map<String,dynamic> _es = {
  "hello": "Hola",
  "choose_image": "Elegir imagen",
  "take_photo": "Tomar foto",
  "choose_from_gallery": "Elegir de la galería",
  "back_to_role_selection": "Volver a la selección de rol",
  "login_as_customer": "Iniciar sesión como cliente",
  "enter_credentials_to_continue": "Ingresa tus credenciales para continuar",
  "continue_with_google": "Continuar con Google",
  "continue_with_apple": "Continuar con Apple",
  "or_continue_with_email": "O continuar con correo electrónico",
  "email_address": "Dirección de correo electrónico",
  "email_placeholder": "you@example.com",
  "password": "Contraseña",
  "password_placeholder": "••••••••",
  "remember_me": "Recordarme",
  "forgot_password": "¿Olvidaste tu contraseña?",
  "login": "Iniciar sesión",
  "dont_have_account": "¿No tienes una cuenta?",
  "register_now": "Regístrate ahora",
  "register_as_customer": "Registrarse como cliente",
  "create_account_to_get_started": "Crea tu cuenta para comenzar",
  "or_register_with_email": "O regístrate con correo electrónico",
  "full_name": "Nombre completo",
  "full_name_placeholder": "Juan Pérez",
  "phone_number": "Número de teléfono",
  "phone_placeholder": "+34 123 456 789",
  "confirm_password": "Confirmar contraseña",
  "confirm_password_placeholder": "••••••••",
  "i_agree_to_the": "Acepto los",
  "terms_of_service": "Términos de Servicio",
  "and": "y",
  "privacy_policy": "Política de Privacidad",
  "create_account": "Crear cuenta",
  "already_have_account": "¿Ya tienes una cuenta?",
  "login_here": "Inicia sesión aquí",
  "discover_egypt": "Descubre Egipto",
  "book_amazing_activities": "Reserva actividades y experiencias increíbles",
  "scan_qr_code": "Escanear código QR",
  "search_activities": "Buscar actividades...",
  "popular_activities": "Actividades populares",
  "special_events": "Eventos especiales",
  "additional_services": "Servicios adicionales",
  "luxor_temple_tour": "Tour del Templo de Luxor",
  "hours": "horas",
  "per_person": "/persona",
  "book": "Reservar",
  "book_now": "Reservar ahora",
  "healthcare": "Atención médica",
  "medical_support": "Soporte médico 24/7",
  "spa_massage": "Spa y masajes",
  "relaxation_services": "Servicios de relajación",
  "request_service": "Solicitar servicio",
  "christmas_beach_party": "Fiesta navideña en la playa",
  "new_year_gala_dinner": "Cena de gala de Año Nuevo",
  "special_event": "Evento especial",
  "december": "Diciembre",
  "cultural": "Cultural",
  "language_english": "English",
  "language_arabic": "العربية",
  "language_german": "Deutsch",
  "language_spanish": "Español",
  "language_french": "Français",
  "language_italian": "Italiano",
  "language_russian": "Русский",
  "home": "Inicio",
  "excursions": "Excursiones",
  "events": "Eventos",
  "services": "Servicios",
  "favorites": "Favoritos",
  "search_placeholder": "Buscar excursiones, eventos...",
  "all": "Todo",
  "snorkeling": "Esnórquel",
  "diving": "Buceo",
  "safari": "Safari",
  "adventure": "Aventura",
  "view_all": "Ver todo",
  "trending_excursions": "Populares",
  "upcoming_events": "Próximos eventos",
  "quick_services": "Servicios rápidos",
  "connect": "Conectar",
  "available": "Disponible",
  "explore_excursions": "Explorar excursiones",
  "my_favorites": "Mis favoritos",
  "no_favorites_yet": "Sin favoritos aún",
  "start_adding_favorites": "¡Añade favoritos ahora!",
  "favorite_excursions": "Excursiones favoritas",
  "favorite_events": "Eventos favoritos",
  "connect_with_representative": "Contactar representante",
  "scan_qr_description": "Escanea el código QR para empezar",
  "close": "Cerrar",
  "select_date": "Fecha",
  "preferred_time": "Hora",
  "number_of_people": "Personas",
  "additional_notes": "Notas",
  "additional_notes_placeholder": "Solicitudes especiales...",
  "price_summary": "Precio",
  "service_fee": "Tarifa",
  "total": "Total",
  "cancel": "Cancelar",
  "confirm_booking": "Confirmar",
  "people": "personas",
  "person": "persona",
  "preferred_date": "Fecha preferida",
  "urgency_level": "Urgencia",
  "normal": "Normal",
  "urgent": "Urgente",
  "emergency": "Emergencia",
  "additional_details": "Detalles",
  "additional_details_placeholder": "Describa sus necesidades...",
  "service_request_info": "Le contactaremos en 30 minutos",
  "submit_request": "Enviar",
  "booking_confirmed": "¡Confirmado!",
  "service_requested": "¡Enviado!",
  "night_life": "Vida nocturna",
  "christmas": "Navidad",
  "new_year": "Año Nuevo",
  "select_time": "Hora",
  "excursion_red_sea_name": "Aventura de Snorkel en el Mar Rojo",
  "excursion_red_sea_desc": "Explora los hermosos arrecifes de coral y la colorida vida marina",
  "excursion_safari_name": "Experiencia de Safari en el Desierto",
  "excursion_safari_desc": "Emocionante aventura en el desierto con quads y paseos en camello",
  "excursion_scuba_name": "Buceo Profesional",
  "excursion_scuba_desc": "Experiencia de buceo en aguas profundas con instructores certificados",
  "excursion_luxor_name": "Tour del Templo de Luxor",
  "excursion_luxor_desc": "Visita templos y monumentos del antiguo Egipto",
  "excursion_bedouin_name": "Safari Nocturno Beduino",
  "excursion_bedouin_desc": "Vive la cultura beduina con cena y observación de estrellas",
  "excursion_parasailing_name": "Aventura de Parasailing",
  "excursion_parasailing_desc": "Vuela sobre el Mar Rojo con vistas impresionantes",
  "event_christmas_party_name": "Fiesta de Navidad en la Playa",
  "event_christmas_party_desc": "Celebra la Navidad en la playa con música y comida",
  "event_new_year_gala_name": "Noche de Gala de Año Nuevo",
  "event_new_year_gala_desc": "Recibe el año nuevo con una celebración espectacular",
  "event_night_club_name": "Experiencia en Club Nocturno",
  "event_night_club_desc": "Experiencia premium en club nocturno con DJs internacionales",
  "event_cultural_night_name": "Noche Cultural Egipcia",
  "event_cultural_night_desc": "Música, danza y cocina tradicional egipcia",
  "service_healthcare_name": "Atención Médica",
  "service_healthcare_desc": "Soporte médico 24/7",
  "service_spa_name": "Spa y Masaje",
  "service_spa_desc": "Servicios de relajación",
  "service_doctor_name": "Consulta Médica",
  "service_doctor_desc": "En línea y en persona",
  "service_transfer_name": "Traslado al Aeropuerto",
  "service_transfer_desc": "Transporte privado",
  "service_trainer_name": "Entrenador Personal",
  "service_trainer_desc": "Fitness y bienestar",
  "service_guide_name": "Guía Turístico",
  "service_guide_desc": "Tours privados"
};
static const Map<String,dynamic> _ar = {
  "hello": "اهلا",
  "choose_image": "اختر الصوره",
  "take_photo": "التقط صورة",
  "choose_from_gallery": "من المعرض",
  "back_to_role_selection": "العودة لاختيار الدور",
  "login_as_customer": "تسجيل الدخول كعميل",
  "enter_credentials_to_continue": "أدخل بياناتك للمتابعة",
  "continue_with_google": "المتابعة مع جوجل",
  "continue_with_apple": "المتابعة مع آبل",
  "or_continue_with_email": "أو المتابعة بالبريد الإلكتروني",
  "email_address": "عنوان البريد الإلكتروني",
  "email_placeholder": "you@example.com",
  "password": "كلمة المرور",
  "password_placeholder": "••••••••",
  "remember_me": "تذكرني",
  "forgot_password": "نسيت كلمة المرور؟",
  "login": "تسجيل الدخول",
  "dont_have_account": "ليس لديك حساب؟",
  "register_now": "سجل الآن",
  "register_as_customer": "التسجيل كعميل",
  "create_account_to_get_started": "أنشئ حسابك للبدء",
  "or_register_with_email": "أو سجل بالبريد الإلكتروني",
  "full_name": "الاسم الكامل",
  "full_name_placeholder": "أحمد محمد",
  "phone_number": "رقم الهاتف",
  "phone_placeholder": "+20 123 456 7890",
  "confirm_password": "تأكيد كلمة المرور",
  "confirm_password_placeholder": "••••••••",
  "i_agree_to_the": "أوافق على",
  "terms_of_service": "شروط الخدمة",
  "and": "و",
  "privacy_policy": "سياسة الخصوصية",
  "create_account": "إنشاء حساب",
  "already_have_account": "لديك حساب بالفعل؟",
  "login_here": "سجل الدخول هنا",
  "discover_egypt": "اكتشف مصر",
  "book_amazing_activities": "احجز أنشطة وتجارب مذهلة",
  "scan_qr_code": "مسح رمز الاستجابة السريعة",
  "search_activities": "البحث عن الأنشطة...",
  "popular_activities": "الأنشطة الشائعة",
  "special_events": "الأحداث الخاصة",
  "additional_services": "خدمات إضافية",
  "luxor_temple_tour": "جولة معبد الأقصر",
  "hours": "ساعات",
  "per_person": "/شخص",
  "book": "احجز",
  "book_now": "احجز الآن",
  "healthcare": "الرعاية الصحية",
  "medical_support": "دعم طبي على مدار الساعة",
  "spa_massage": "سبا ومساج",
  "relaxation_services": "خدمات الاسترخاء",
  "request_service": "طلب الخدمة",
  "christmas_beach_party": "حفلة شاطئ عيد الميلاد",
  "new_year_gala_dinner": "عشاء احتفالي رأس السنة",
  "special_event": "حدث خاص",
  "december": "ديسمبر",
  "cultural": "ثقافي",
  "home": "الرئيسية",
  "excursions": "الرحلات",
  "events": "الفعاليات",
  "services": "الخدمات",
  "favorites": "المفضلة",
  "search_placeholder": "البحث عن الرحلات أو الفعاليات أو الخدمات...",
  "all": "الكل",
  "snorkeling": "الغطس",
  "diving": "الغوص",
  "safari": "سفاري",
  "adventure": "مغامرة",
  "view_all": "عرض الكل",
  "trending_excursions": "الرحلات الرائجة",
  "upcoming_events": "الفعاليات القادمة",
  "quick_services": "خدمات سريعة",
  "connect": "اتصل",
  "available": "متاح",
  "explore_excursions": "استكشف الرحلات",
  "my_favorites": "مفضلاتي",
  "no_favorites_yet": "لا توجد مفضلات بعد",
  "start_adding_favorites": "ابدأ بإضافة الرحلات والفعاليات إلى مفضلاتك!",
  "favorite_excursions": "الرحلات المفضلة",
  "favorite_events": "الفعاليات المفضلة",
  "connect_with_representative": "اتصل بالممثل",
  "scan_qr_description": "امسح رمز الاستجابة السريعة الخاص بممثلك للبدء",
  "close": "إغلاق",
  "select_date": "اختر التاريخ",
  "preferred_time": "الوقت المفضل",
  "number_of_people": "عدد الأشخاص",
  "additional_notes": "ملاحظات إضافية",
  "additional_notes_placeholder": "أي طلبات أو متطلبات خاصة...",
  "price_summary": "ملخص السعر",
  "service_fee": "رسوم الخدمة",
  "total": "الإجمالي",
  "cancel": "إلغاء",
  "confirm_booking": "تأكيد الحجز",
  "people": "أشخاص",
  "person": "شخص",
  "preferred_date": "التاريخ المفضل",
  "urgency_level": "مستوى الأولوية",
  "normal": "عادي",
  "urgent": "عاجل",
  "emergency": "طارئ",
  "additional_details": "تفاصيل إضافية",
  "additional_details_placeholder": "يرجى وصف احتياجاتك أو أي متطلبات خاصة...",
  "service_request_info": "سيتواصل فريقنا معك خلال 30 دقيقة لتأكيد طلب الخدمة",
  "submit_request": "إرسال الطلب",
  "booking_confirmed": "تم تأكيد الحجز!",
  "service_requested": "تم إرسال طلب الخدمة!",
  "night_life": "الحياة الليلية",
  "christmas": "عيد الميلاد",
  "new_year": "رأس السنة",
  "select_time": "اختر الوقت",
  "excursion_red_sea_name": "مغامرة الغوص في البحر الأحمر",
  "excursion_red_sea_desc": "استكشف الشعاب المرجانية الجميلة والحياة البحرية الملونة",
  "excursion_safari_name": "تجربة سفاري الصحراء",
  "excursion_safari_desc": "مغامرة صحراوية مثيرة مع الدراجات الرباعية وركوب الجمال",
  "excursion_scuba_name": "غوص سكوبا احترافي",
  "excursion_scuba_desc": "تجربة غوص في أعماق البحار مع مدربين معتمدين",
  "excursion_luxor_name": "جولة معبد الأقصر",
  "excursion_luxor_desc": "زيارة المعابد والآثار المصرية القديمة",
  "excursion_bedouin_name": "سفاري ليلي بدوي",
  "excursion_bedouin_desc": "تجربة الثقافة البدوية مع العشاء وتأمل النجوم",
  "excursion_parasailing_name": "مغامرة الباراشوت",
  "excursion_parasailing_desc": "حلق فوق البحر الأحمر مع مناظر خلابة",
  "event_christmas_party_name": "حفلة شاطئ الكريسماس",
  "event_christmas_party_desc": "احتفل بالكريسماس على الشاطئ مع الموسيقى والطعام",
  "event_new_year_gala_name": "حفل رأس السنة",
  "event_new_year_gala_desc": "استقبل العام الجديد باحتفال رائع",
  "event_night_club_name": "تجربة النادي الليلي",
  "event_night_club_desc": "تجربة نادي ليلي مميز مع دي جي عالميين",
  "event_cultural_night_name": "ليلة ثقافية مصرية",
  "event_cultural_night_desc": "موسيقى ورقص ومأكولات مصرية تقليدية",
  "service_healthcare_name": "رعاية صحية",
  "service_healthcare_desc": "دعم طبي على مدار 24 ساعة",
  "service_spa_name": "سبا وتدليك",
  "service_spa_desc": "خدمات الاسترخاء",
  "service_doctor_name": "استشارة طبيب",
  "service_doctor_desc": "عبر الإنترنت وشخصياً",
  "service_transfer_name": "نقل المطار",
  "service_transfer_desc": "نقل خاص",
  "service_trainer_name": "مدرب شخصي",
  "service_trainer_desc": "لياقة بدنية وصحة",
  "service_guide_name": "مرشد سياحي",
  "service_guide_desc": "جولات خاصة"
};
static const Map<String, Map<String,dynamic>> mapLocales = {"de": _de, "ru": _ru, "en": _en, "it": _it, "fr": _fr, "es": _es, "ar": _ar};
}
