// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

// ignore_for_file: prefer_single_quotes, avoid_renaming_method_parameters, constant_identifier_names

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

class CodegenLoader extends AssetLoader{
  const CodegenLoader();

  @override
  Future<Map<String, dynamic>?> load(String path, Locale locale) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static const Map<String,dynamic> _de = {
  "hello": "Hallo",
  "choose_image": "Bild auswählen",
  "take_photo": "Foto aufnehmen",
  "choose_from_gallery": "Aus der Galerie wählen",
  "back_to_role_selection": "Zurück zur Rollenauswahl",
  "login_as_customer": "Als Kunde anmelden",
  "enter_credentials_to_continue": "Geben Sie Ihre Anmeldedaten ein, um fortzufahren",
  "continue_with_google": "Mit Google fortfahren",
  "continue_with_apple": "Mit Apple fortfahren",
  "or_continue_with_email": "Oder mit E-Mail fortfahren",
  "email_address": "E-Mail-Adresse",
  "email_placeholder": "you@example.com",
  "password": "Passwort",
  "password_placeholder": "••••••••",
  "remember_me": "Angemeldet bleiben",
  "forgot_password": "Passwort vergessen?",
  "login": "Anmelden",
  "dont_have_account": "Haben Sie noch kein Konto?",
  "register_now": "Jetzt registrieren",
  "register_as_customer": "Als Kunde registrieren",
  "create_account_to_get_started": "Erstellen Sie Ihr Konto, um zu beginnen",
  "or_register_with_email": "Oder mit E-Mail registrieren",
  "full_name": "Vollständiger Name",
  "full_name_placeholder": "Max Mustermann",
  "phone_number": "Telefonnummer",
  "phone_placeholder": "+49 123 456 7890",
  "confirm_password": "Passwort bestätigen",
  "confirm_password_placeholder": "••••••••",
  "i_agree_to_the": "Ich stimme den",
  "terms_of_service": "Nutzungsbedingungen",
  "and": "und",
  "privacy_policy": "Datenschutzrichtlinie",
  "create_account": "Konto erstellen",
  "already_have_account": "Haben Sie bereits ein Konto?",
  "login_here": "Hier anmelden",
  "discover_egypt": "Ägypten entdecken",
  "book_amazing_activities": "Buchen Sie erstaunliche Aktivitäten und Erlebnisse",
  "scan_qr_code": "QR-Code scannen",
  "search_activities": "Aktivitäten suchen...",
  "popular_activities": "Beliebte Aktivitäten",
  "special_events": "Besondere Veranstaltungen",
  "additional_services": "Zusätzliche Dienstleistungen",
  "luxor_temple_tour": "Luxor Tempel Tour",
  "hours": "Stunden",
  "per_person": "/Person",
  "book": "Buchen",
  "book_now": "Jetzt buchen",
  "healthcare": "Gesundheitswesen",
  "medical_support": "24/7 Medizinische Unterstützung",
  "spa_massage": "Spa & Massage",
  "relaxation_services": "Entspannungsdienstleistungen",
  "request_service": "Service anfordern",
  "christmas_beach_party": "Weihnachts-Strandparty",
  "new_year_gala_dinner": "Neujahrs-Gala-Dinner",
  "special_event": "Besonderes Ereignis",
  "december": "Dezember",
  "cultural": "Kulturell"
};
static const Map<String,dynamic> _ru = {
  "hello": "Привет",
  "choose_image": "Выбрать изображение",
  "take_photo": "Сделать фото",
  "choose_from_gallery": "Выбрать из галереи",
  "back_to_role_selection": "Вернуться к выбору роли",
  "login_as_customer": "Войти как клиент",
  "enter_credentials_to_continue": "Введите свои данные для продолжения",
  "continue_with_google": "Продолжить с Google",
  "continue_with_apple": "Продолжить с Apple",
  "or_continue_with_email": "Или продолжить с электронной почтой",
  "email_address": "Адрес электронной почты",
  "email_placeholder": "you@example.com",
  "password": "Пароль",
  "password_placeholder": "••••••••",
  "remember_me": "Запомнить меня",
  "forgot_password": "Забыли пароль?",
  "login": "Войти",
  "dont_have_account": "Нет аккаунта?",
  "register_now": "Зарегистрироваться сейчас",
  "register_as_customer": "Зарегистрироваться как клиент",
  "create_account_to_get_started": "Создайте свой аккаунт, чтобы начать",
  "or_register_with_email": "Или зарегистрироваться с электронной почтой",
  "full_name": "Полное имя",
  "full_name_placeholder": "Иван Иванов",
  "phone_number": "Номер телефона",
  "phone_placeholder": "+7 123 456 7890",
  "confirm_password": "Подтвердить пароль",
  "confirm_password_placeholder": "••••••••",
  "i_agree_to_the": "Я согласен с",
  "terms_of_service": "Условиями обслуживания",
  "and": "и",
  "privacy_policy": "Политикой конфиденциальности",
  "create_account": "Создать аккаунт",
  "already_have_account": "Уже есть аккаунт?",
  "login_here": "Войти здесь",
  "discover_egypt": "Откройте Египет",
  "book_amazing_activities": "Забронируйте удивительные мероприятия и впечатления",
  "scan_qr_code": "Сканировать QR-код",
  "search_activities": "Поиск мероприятий...",
  "popular_activities": "Популярные мероприятия",
  "special_events": "Специальные события",
  "additional_services": "Дополнительные услуги",
  "luxor_temple_tour": "Экскурсия по храму Луксора",
  "hours": "часов",
  "per_person": "/человек",
  "book": "Забронировать",
  "book_now": "Забронировать сейчас",
  "healthcare": "Здравоохранение",
  "medical_support": "Медицинская поддержка 24/7",
  "spa_massage": "Спа и массаж",
  "relaxation_services": "Услуги релаксации",
  "request_service": "Запросить услугу",
  "christmas_beach_party": "Рождественская пляжная вечеринка",
  "new_year_gala_dinner": "Новогодний гала-ужин",
  "special_event": "Специальное событие",
  "december": "Декабрь",
  "cultural": "Культурный"
};
static const Map<String,dynamic> _en = {
  "hello": "Hello",
  "choose_image": "Choose Image",
  "take_photo": "Take Photo",
  "choose_from_gallery": "Choose from Gallery",
  "back_to_role_selection": "Back to role selection",
  "login_as_customer": "Login as Customer",
  "enter_credentials_to_continue": "Enter your credentials to continue",
  "continue_with_google": "Continue with Google",
  "continue_with_apple": "Continue with Apple",
  "or_continue_with_email": "Or continue with email",
  "email_address": "Email Address",
  "email_placeholder": "you@example.com",
  "password": "Password",
  "password_placeholder": "••••••••",
  "remember_me": "Remember me",
  "forgot_password": "Forgot password?",
  "login": "Login",
  "dont_have_account": "Don't have an account?",
  "register_now": "Register Now",
  "language_english": "English",
  "language_arabic": "العربية",
  "language_german": "Deutsch",
  "language_spanish": "Español",
  "language_french": "Français",
  "language_italian": "Italiano",
  "language_russian": "Русский",
  "register_as_customer": "Register as Customer",
  "create_account_to_get_started": "Create your account to get started",
  "or_register_with_email": "Or register with email",
  "full_name": "Full Name",
  "full_name_placeholder": "John Doe",
  "phone_number": "Phone Number",
  "phone_placeholder": "+20 123 456 7890",
  "confirm_password": "Confirm Password",
  "confirm_password_placeholder": "••••••••",
  "i_agree_to_the": "I agree to the",
  "terms_of_service": "Terms of Service",
  "and": "and",
  "privacy_policy": "Privacy Policy",
  "create_account": "Create Account",
  "already_have_account": "Already have an account?",
  "login_here": "Login Here",
  "discover_egypt": "Discover Egypt",
  "book_amazing_activities": "Book amazing activities and experiences",
  "scan_qr_code": "Scan QR Code",
  "search_activities": "Search activities...",
  "popular_activities": "Popular Activities",
  "special_events": "Special Events",
  "additional_services": "Additional Services",
  "luxor_temple_tour": "Luxor Temple Tour",
  "hours": "hours",
  "per_person": "/person",
  "book": "Book",
  "book_now": "Book Now",
  "healthcare": "Healthcare",
  "medical_support": "24/7 Medical Support",
  "spa_massage": "Spa & Massage",
  "relaxation_services": "Relaxation Services",
  "request_service": "Request Service",
  "christmas_beach_party": "Christmas Beach Party",
  "new_year_gala_dinner": "New Year Gala Dinner",
  "special_event": "Special Event",
  "december": "December",
  "cultural": "Cultural"
};
static const Map<String,dynamic> _it = {
  "hello": "Ciao",
  "choose_image": "Scegli immagine",
  "take_photo": "Scatta foto",
  "choose_from_gallery": "Scegli dalla galleria",
  "back_to_role_selection": "Torna alla selezione del ruolo",
  "login_as_customer": "Accedi come cliente",
  "enter_credentials_to_continue": "Inserisci le tue credenziali per continuare",
  "continue_with_google": "Continua con Google",
  "continue_with_apple": "Continua con Apple",
  "or_continue_with_email": "O continua con l'email",
  "email_address": "Indirizzo email",
  "email_placeholder": "you@example.com",
  "password": "Password",
  "password_placeholder": "••••••••",
  "remember_me": "Ricordami",
  "forgot_password": "Password dimenticata?",
  "login": "Accedi",
  "dont_have_account": "Non hai un account?",
  "register_now": "Registrati ora",
  "register_as_customer": "Registrati come cliente",
  "create_account_to_get_started": "Crea il tuo account per iniziare",
  "or_register_with_email": "O registrati con l'email",
  "full_name": "Nome completo",
  "full_name_placeholder": "Mario Rossi",
  "phone_number": "Numero di telefono",
  "phone_placeholder": "+39 123 456 7890",
  "confirm_password": "Conferma password",
  "confirm_password_placeholder": "••••••••",
  "i_agree_to_the": "Accetto i",
  "terms_of_service": "Termini di Servizio",
  "and": "e",
  "privacy_policy": "Informativa sulla Privacy",
  "create_account": "Crea account",
  "already_have_account": "Hai già un account?",
  "login_here": "Accedi qui",
  "discover_egypt": "Scopri l'Egitto",
  "book_amazing_activities": "Prenota attività ed esperienze incredibili",
  "scan_qr_code": "Scansiona codice QR",
  "search_activities": "Cerca attività...",
  "popular_activities": "Attività popolari",
  "special_events": "Eventi speciali",
  "additional_services": "Servizi aggiuntivi",
  "luxor_temple_tour": "Tour del Tempio di Luxor",
  "hours": "ore",
  "per_person": "/persona",
  "book": "Prenota",
  "book_now": "Prenota ora",
  "healthcare": "Assistenza sanitaria",
  "medical_support": "Supporto medico 24/7",
  "spa_massage": "Spa e massaggi",
  "relaxation_services": "Servizi di rilassamento",
  "request_service": "Richiedi servizio",
  "christmas_beach_party": "Festa di Natale in spiaggia",
  "new_year_gala_dinner": "Cena di gala di Capodanno",
  "special_event": "Evento speciale",
  "december": "Dicembre",
  "cultural": "Culturale"
};
static const Map<String,dynamic> _fr = {
  "hello": "Bonjour",
  "choose_image": "Choisir une image",
  "take_photo": "Prendre une photo",
  "choose_from_gallery": "Choisir dans la galerie",
  "back_to_role_selection": "Retour à la sélection de rôle",
  "login_as_customer": "Se connecter en tant que client",
  "enter_credentials_to_continue": "Entrez vos identifiants pour continuer",
  "continue_with_google": "Continuer avec Google",
  "continue_with_apple": "Continuer avec Apple",
  "or_continue_with_email": "Ou continuer avec l'e-mail",
  "email_address": "Adresse e-mail",
  "email_placeholder": "you@example.com",
  "password": "Mot de passe",
  "password_placeholder": "••••••••",
  "remember_me": "Se souvenir de moi",
  "forgot_password": "Mot de passe oublié ?",
  "login": "Se connecter",
  "dont_have_account": "Vous n'avez pas de compte ?",
  "register_now": "S'inscrire maintenant",
  "register_as_customer": "S'inscrire en tant que client",
  "create_account_to_get_started": "Créez votre compte pour commencer",
  "or_register_with_email": "Ou s'inscrire avec l'e-mail",
  "full_name": "Nom complet",
  "full_name_placeholder": "Jean Dupont",
  "phone_number": "Numéro de téléphone",
  "phone_placeholder": "+33 1 23 45 67 89",
  "confirm_password": "Confirmer le mot de passe",
  "confirm_password_placeholder": "••••••••",
  "i_agree_to_the": "J'accepte les",
  "terms_of_service": "Conditions de Service",
  "and": "et",
  "privacy_policy": "Politique de Confidentialité",
  "create_account": "Créer un compte",
  "already_have_account": "Vous avez déjà un compte ?",
  "login_here": "Connectez-vous ici",
  "discover_egypt": "Découvrir l'Égypte",
  "book_amazing_activities": "Réservez des activités et expériences incroyables",
  "scan_qr_code": "Scanner le code QR",
  "search_activities": "Rechercher des activités...",
  "popular_activities": "Activités populaires",
  "special_events": "Événements spéciaux",
  "additional_services": "Services supplémentaires",
  "luxor_temple_tour": "Visite du temple de Louxor",
  "hours": "heures",
  "per_person": "/personne",
  "book": "Réserver",
  "book_now": "Réserver maintenant",
  "healthcare": "Soins de santé",
  "medical_support": "Support médical 24/7",
  "spa_massage": "Spa et massage",
  "relaxation_services": "Services de relaxation",
  "request_service": "Demander un service",
  "christmas_beach_party": "Fête de Noël sur la plage",
  "new_year_gala_dinner": "Dîner de gala du Nouvel An",
  "special_event": "Événement spécial",
  "december": "Décembre",
  "cultural": "Culturel"
};
static const Map<String,dynamic> _es = {
  "hello": "Hola",
  "choose_image": "Elegir imagen",
  "take_photo": "Tomar foto",
  "choose_from_gallery": "Elegir de la galería",
  "back_to_role_selection": "Volver a la selección de rol",
  "login_as_customer": "Iniciar sesión como cliente",
  "enter_credentials_to_continue": "Ingresa tus credenciales para continuar",
  "continue_with_google": "Continuar con Google",
  "continue_with_apple": "Continuar con Apple",
  "or_continue_with_email": "O continuar con correo electrónico",
  "email_address": "Dirección de correo electrónico",
  "email_placeholder": "you@example.com",
  "password": "Contraseña",
  "password_placeholder": "••••••••",
  "remember_me": "Recordarme",
  "forgot_password": "¿Olvidaste tu contraseña?",
  "login": "Iniciar sesión",
  "dont_have_account": "¿No tienes una cuenta?",
  "register_now": "Regístrate ahora",
  "register_as_customer": "Registrarse como cliente",
  "create_account_to_get_started": "Crea tu cuenta para comenzar",
  "or_register_with_email": "O regístrate con correo electrónico",
  "full_name": "Nombre completo",
  "full_name_placeholder": "Juan Pérez",
  "phone_number": "Número de teléfono",
  "phone_placeholder": "+34 123 456 789",
  "confirm_password": "Confirmar contraseña",
  "confirm_password_placeholder": "••••••••",
  "i_agree_to_the": "Acepto los",
  "terms_of_service": "Términos de Servicio",
  "and": "y",
  "privacy_policy": "Política de Privacidad",
  "create_account": "Crear cuenta",
  "already_have_account": "¿Ya tienes una cuenta?",
  "login_here": "Inicia sesión aquí",
  "discover_egypt": "Descubre Egipto",
  "book_amazing_activities": "Reserva actividades y experiencias increíbles",
  "scan_qr_code": "Escanear código QR",
  "search_activities": "Buscar actividades...",
  "popular_activities": "Actividades populares",
  "special_events": "Eventos especiales",
  "additional_services": "Servicios adicionales",
  "luxor_temple_tour": "Tour del Templo de Luxor",
  "hours": "horas",
  "per_person": "/persona",
  "book": "Reservar",
  "book_now": "Reservar ahora",
  "healthcare": "Atención médica",
  "medical_support": "Soporte médico 24/7",
  "spa_massage": "Spa y masajes",
  "relaxation_services": "Servicios de relajación",
  "request_service": "Solicitar servicio",
  "christmas_beach_party": "Fiesta navideña en la playa",
  "new_year_gala_dinner": "Cena de gala de Año Nuevo",
  "special_event": "Evento especial",
  "december": "Diciembre",
  "cultural": "Cultural"
};
static const Map<String,dynamic> _ar = {
  "hello": "اهلا",
  "choose_image": "اختر الصوره",
  "take_photo": "التقط صورة",
  "choose_from_gallery": "من المعرض",
  "back_to_role_selection": "العودة لاختيار الدور",
  "login_as_customer": "تسجيل الدخول كعميل",
  "enter_credentials_to_continue": "أدخل بياناتك للمتابعة",
  "continue_with_google": "المتابعة مع جوجل",
  "continue_with_apple": "المتابعة مع آبل",
  "or_continue_with_email": "أو المتابعة بالبريد الإلكتروني",
  "email_address": "عنوان البريد الإلكتروني",
  "email_placeholder": "you@example.com",
  "password": "كلمة المرور",
  "password_placeholder": "••••••••",
  "remember_me": "تذكرني",
  "forgot_password": "نسيت كلمة المرور؟",
  "login": "تسجيل الدخول",
  "dont_have_account": "ليس لديك حساب؟",
  "register_now": "سجل الآن",
  "register_as_customer": "التسجيل كعميل",
  "create_account_to_get_started": "أنشئ حسابك للبدء",
  "or_register_with_email": "أو سجل بالبريد الإلكتروني",
  "full_name": "الاسم الكامل",
  "full_name_placeholder": "أحمد محمد",
  "phone_number": "رقم الهاتف",
  "phone_placeholder": "+20 123 456 7890",
  "confirm_password": "تأكيد كلمة المرور",
  "confirm_password_placeholder": "••••••••",
  "i_agree_to_the": "أوافق على",
  "terms_of_service": "شروط الخدمة",
  "and": "و",
  "privacy_policy": "سياسة الخصوصية",
  "create_account": "إنشاء حساب",
  "already_have_account": "لديك حساب بالفعل؟",
  "login_here": "سجل الدخول هنا",
  "discover_egypt": "اكتشف مصر",
  "book_amazing_activities": "احجز أنشطة وتجارب مذهلة",
  "scan_qr_code": "مسح رمز الاستجابة السريعة",
  "search_activities": "البحث عن الأنشطة...",
  "popular_activities": "الأنشطة الشائعة",
  "special_events": "الأحداث الخاصة",
  "additional_services": "خدمات إضافية",
  "luxor_temple_tour": "جولة معبد الأقصر",
  "hours": "ساعات",
  "per_person": "/شخص",
  "book": "احجز",
  "book_now": "احجز الآن",
  "healthcare": "الرعاية الصحية",
  "medical_support": "دعم طبي على مدار الساعة",
  "spa_massage": "سبا ومساج",
  "relaxation_services": "خدمات الاسترخاء",
  "request_service": "طلب الخدمة",
  "christmas_beach_party": "حفلة شاطئ عيد الميلاد",
  "new_year_gala_dinner": "عشاء احتفالي رأس السنة",
  "special_event": "حدث خاص",
  "december": "ديسمبر",
  "cultural": "ثقافي"
};
static const Map<String, Map<String,dynamic>> mapLocales = {"de": _de, "ru": _ru, "en": _en, "it": _it, "fr": _fr, "es": _es, "ar": _ar};
}
